CREATE TABLE stations (
    id varchar(128) PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    homepage_url text,
    tags text[] NOT NULL DEFAULT '{}' CHECK (array_position(tags, '') IS NULL),
    language varchar(3) CHECK (language ~ '^[a-z]{2,3}$'),
    country_code char(2) CHECK (country_code ~ '^[A-Z]{2}$'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE station_streams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id varchar(128) NOT NULL REFERENCES stations(id) ON DELETE CASCADE,
    stream_url text NOT NULL UNIQUE CHECK (btrim(stream_url) <> ''),
    codec text,
    bitrate_kbps integer CHECK (bitrate_kbps > 0),
    health text NOT NULL DEFAULT 'unknown' CHECK (health IN ('healthy', 'degraded', 'unknown')),
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX stations_language_country_idx ON stations (language, country_code);
CREATE INDEX stations_tags_idx ON stations USING gin (tags);
CREATE INDEX station_streams_station_id_idx ON station_streams (station_id);
CREATE UNIQUE INDEX station_streams_one_primary_idx
    ON station_streams (station_id)
    WHERE is_primary;
