-- Genre taxonomy with parent-child hierarchy for progressive search fallback.
-- Generated from SoundStock music-genres-taxonomy dataset.
-- Self-referencing FK is checked after all inserts via a deferred constraint.

CREATE TABLE genre_hierarchy (
    tag varchar(64) PRIMARY KEY,
    parent_tag varchar(64),
    display_name varchar(128) NOT NULL,
    is_canonical boolean NOT NULL DEFAULT true
);

CREATE INDEX genre_hierarchy_parent_idx ON genre_hierarchy (parent_tag);

-- Level 0 (24 entries)
INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('rock', NULL, 'Rock'),
('pop', NULL, 'Pop'),
('hip hop', NULL, 'Hip Hop'),
('r&b', NULL, 'R&B'),
('electronic', NULL, 'Electronic'),
('dance', NULL, 'Dance'),
('jazz', NULL, 'Jazz'),
('blues', NULL, 'Blues'),
('country', NULL, 'Country'),
('folk', NULL, 'Folk'),
('classical', NULL, 'Classical'),
('metal', NULL, 'Metal'),
('punk', NULL, 'Punk'),
('reggae', NULL, 'Reggae'),
('latin', NULL, 'Latin'),
('soul & funk', NULL, 'Soul & Funk'),
('gospel', NULL, 'Gospel'),
('world', NULL, 'World'),
('soundtrack', NULL, 'Soundtrack'),
('experimental', NULL, 'Experimental'),
('ambient', NULL, 'Ambient'),
('children', NULL, 'Children'),
('comedy', NULL, 'Comedy'),
('spoken word', NULL, 'Spoken Word')
ON CONFLICT (tag) DO NOTHING;

-- Level 1 (329 entries)
INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('alternative rock', 'rock', 'Alternative Rock'),
('indie rock', 'rock', 'Indie Rock'),
('hard rock', 'rock', 'Hard Rock'),
('classic rock', 'rock', 'Classic Rock'),
('progressive rock', 'rock', 'Progressive Rock'),
('psychedelic rock', 'rock', 'Psychedelic Rock'),
('garage rock', 'rock', 'Garage Rock'),
('surf rock', 'rock', 'Surf Rock'),
('post-rock', 'rock', 'Post-Rock'),
('art rock', 'rock', 'Art Rock'),
('southern rock', 'rock', 'Southern Rock'),
('stoner rock', 'rock', 'Stoner Rock'),
('noise rock', 'rock', 'Noise Rock'),
('math rock', 'rock', 'Math Rock'),
('arena rock', 'rock', 'Arena Rock'),
('shoegaze', 'rock', 'Shoegaze'),
('dream pop', 'rock', 'Dream Pop'),
('britpop', 'rock', 'Britpop'),
('grunge', 'rock', 'Grunge'),
('post-punk revival', 'rock', 'Post-Punk Revival'),
('glam rock', 'rock', 'Glam Rock'),
('rockabilly', 'rock', 'Rockabilly'),
('folk rock', 'rock', 'Folk Rock'),
('blues rock', 'rock', 'Blues Rock'),
('symphonic rock', 'rock', 'Symphonic Rock'),
('dance pop', 'pop', 'Dance Pop'),
('electropop', 'pop', 'Electropop'),
('synthpop', 'pop', 'Synthpop'),
('indie pop', 'pop', 'Indie Pop'),
('teen pop', 'pop', 'Teen Pop'),
('art pop', 'pop', 'Art Pop'),
('hyperpop', 'pop', 'Hyperpop'),
('k-pop', 'pop', 'K-Pop'),
('j-pop', 'pop', 'J-Pop'),
('c-pop', 'pop', 'C-Pop'),
('city pop', 'pop', 'City Pop'),
('power pop', 'pop', 'Power Pop'),
('bubblegum pop', 'pop', 'Bubblegum Pop'),
('chamber pop', 'pop', 'Chamber Pop'),
('pop rock', 'pop', 'Pop Rock'),
('adult contemporary', 'pop', 'Adult Contemporary'),
('contemporary pop', 'pop', 'Contemporary Pop'),
('pop punk', 'pop', 'Pop Punk'),
('latin pop', 'pop', 'Latin Pop'),
('europop', 'pop', 'Europop'),
('nordic pop', 'pop', 'Nordic Pop'),
('afropop', 'pop', 'Afropop'),
('arabic pop', 'pop', 'Arabic Pop'),
('boom bap', 'hip hop', 'Boom Bap'),
('trap', 'hip hop', 'Trap')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('drill', 'hip hop', 'Drill'),
('g-funk', 'hip hop', 'G-Funk'),
('west coast hip hop', 'hip hop', 'West Coast Hip Hop'),
('east coast hip hop', 'hip hop', 'East Coast Hip Hop'),
('southern hip hop', 'hip hop', 'Southern Hip Hop'),
('alternative hip hop', 'hip hop', 'Alternative Hip Hop'),
('conscious hip hop', 'hip hop', 'Conscious Hip Hop'),
('hardcore hip hop', 'hip hop', 'Hardcore Hip Hop'),
('cloud rap', 'hip hop', 'Cloud Rap'),
('lo-fi hip hop', 'hip hop', 'Lo-Fi Hip Hop'),
('jazz rap', 'hip hop', 'Jazz Rap'),
('uk hip hop', 'hip hop', 'UK Hip Hop'),
('french hip hop', 'hip hop', 'French Hip Hop'),
('grime', 'hip hop', 'Grime'),
('mumble rap', 'hip hop', 'Mumble Rap'),
('crunk', 'hip hop', 'Crunk'),
('hyphy', 'hip hop', 'Hyphy'),
('chopped and screwed', 'hip hop', 'Chopped and Screwed'),
('phonk', 'hip hop', 'Phonk'),
('memphis rap', 'hip hop', 'Memphis Rap'),
('trap metal', 'hip hop', 'Trap Metal'),
('emo rap', 'hip hop', 'Emo Rap'),
('latin trap', 'hip hop', 'Latin Trap'),
('contemporary r&b', 'r&b', 'Contemporary R&B'),
('neo soul', 'r&b', 'Neo Soul'),
('quiet storm', 'r&b', 'Quiet Storm'),
('alternative r&b', 'r&b', 'Alternative R&B'),
('new jack swing', 'r&b', 'New Jack Swing'),
('r&b pop', 'r&b', 'R&B Pop'),
('smooth r&b', 'r&b', 'Smooth R&B'),
('progressive r&b', 'r&b', 'Progressive R&B'),
('soulful r&b', 'r&b', 'Soulful R&B'),
('funk r&b', 'r&b', 'Funk R&B'),
('uk r&b', 'r&b', 'UK R&B'),
('90s r&b', 'r&b', '90s R&B'),
('motown r&b', 'r&b', 'Motown R&B'),
('modern soul', 'r&b', 'Modern Soul'),
('bedroom r&b', 'r&b', 'Bedroom R&B'),
('house', 'electronic', 'House'),
('techno', 'electronic', 'Techno'),
('trance', 'electronic', 'Trance'),
('drum and bass', 'electronic', 'Drum and Bass'),
('dubstep', 'electronic', 'Dubstep'),
('idm', 'electronic', 'IDM'),
('breakbeat', 'electronic', 'Breakbeat'),
('electro', 'electronic', 'Electro'),
('electronica', 'electronic', 'Electronica'),
('ambient techno', 'electronic', 'Ambient Techno'),
('downtempo', 'electronic', 'Downtempo'),
('trip hop', 'electronic', 'Trip Hop')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('garage', 'electronic', 'Garage'),
('uk garage', 'electronic', 'UK Garage'),
('jungle', 'electronic', 'Jungle'),
('hardstyle', 'electronic', 'Hardstyle'),
('gabber', 'electronic', 'Gabber'),
('glitch', 'electronic', 'Glitch'),
('future bass', 'electronic', 'Future Bass'),
('synthwave', 'electronic', 'Synthwave'),
('vaporwave', 'electronic', 'Vaporwave'),
('chillwave', 'electronic', 'Chillwave'),
('industrial', 'electronic', 'Industrial'),
('ebm', 'electronic', 'EBM'),
('big beat', 'electronic', 'Big Beat'),
('edm', 'dance', 'EDM'),
('dancehall', 'dance', 'Dancehall'),
('eurodance', 'dance', 'Eurodance'),
('disco', 'dance', 'Disco'),
('nu-disco', 'dance', 'Nu-Disco'),
('hi-nrg', 'dance', 'Hi-NRG'),
('italo disco', 'dance', 'Italo Disco'),
('dance-punk', 'dance', 'Dance-Punk'),
('freestyle', 'dance', 'Freestyle'),
('hard dance', 'dance', 'Hard Dance'),
('hands up', 'dance', 'Hands Up'),
('electro house', 'dance', 'Electro House'),
('deep house', 'dance', 'Deep House'),
('progressive house', 'dance', 'Progressive House'),
('tech house', 'dance', 'Tech House'),
('minimal techno', 'dance', 'Minimal Techno'),
('hard techno', 'dance', 'Hard Techno'),
('psytrance', 'dance', 'Psytrance'),
('bebop', 'jazz', 'Bebop'),
('hard bop', 'jazz', 'Hard Bop'),
('cool jazz', 'jazz', 'Cool Jazz'),
('modal jazz', 'jazz', 'Modal Jazz'),
('free jazz', 'jazz', 'Free Jazz'),
('fusion', 'jazz', 'Fusion'),
('smooth jazz', 'jazz', 'Smooth Jazz'),
('latin jazz', 'jazz', 'Latin Jazz'),
('swing', 'jazz', 'Swing'),
('big band', 'jazz', 'Big Band'),
('gypsy jazz', 'jazz', 'Gypsy Jazz'),
('nu jazz', 'jazz', 'Nu Jazz'),
('acid jazz', 'jazz', 'Acid Jazz'),
('contemporary jazz', 'jazz', 'Contemporary Jazz'),
('avant-garde jazz', 'jazz', 'Avant-Garde Jazz'),
('vocal jazz', 'jazz', 'Vocal Jazz'),
('delta blues', 'blues', 'Delta Blues'),
('chicago blues', 'blues', 'Chicago Blues'),
('texas blues', 'blues', 'Texas Blues')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('piedmont blues', 'blues', 'Piedmont Blues'),
('jump blues', 'blues', 'Jump Blues'),
('electric blues', 'blues', 'Electric Blues'),
('country blues', 'blues', 'Country Blues'),
('blues revival', 'blues', 'Blues Revival'),
('soul blues', 'blues', 'Soul Blues'),
('outlaw country', 'country', 'Outlaw Country'),
('country pop', 'country', 'Country Pop'),
('country rock', 'country', 'Country Rock'),
('bluegrass', 'country', 'Bluegrass'),
('americana', 'country', 'Americana'),
('contemporary country', 'country', 'Contemporary Country'),
('honky-tonk', 'country', 'Honky-Tonk'),
('alt-country', 'country', 'Alt-Country'),
('bakersfield sound', 'country', 'Bakersfield Sound'),
('nashville sound', 'country', 'Nashville Sound'),
('red dirt', 'country', 'Red Dirt'),
('bro-country', 'country', 'Bro-Country'),
('neotraditional country', 'country', 'Neotraditional Country'),
('contemporary folk', 'folk', 'Contemporary Folk'),
('traditional folk', 'folk', 'Traditional Folk'),
('indie folk', 'folk', 'Indie Folk'),
('freak folk', 'folk', 'Freak Folk'),
('celtic folk', 'folk', 'Celtic Folk'),
('nordic folk', 'folk', 'Nordic Folk'),
('appalachian folk', 'folk', 'Appalachian Folk'),
('singer-songwriter', 'folk', 'Singer-Songwriter'),
('folk punk', 'folk', 'Folk Punk'),
('folk pop', 'folk', 'Folk Pop'),
('world folk', 'folk', 'World Folk'),
('baroque', 'classical', 'Baroque'),
('classical period', 'classical', 'Classical Period'),
('romantic', 'classical', 'Romantic'),
('modern classical', 'classical', 'Modern Classical'),
('contemporary classical', 'classical', 'Contemporary Classical'),
('opera', 'classical', 'Opera'),
('chamber music', 'classical', 'Chamber Music'),
('symphony', 'classical', 'Symphony'),
('choral', 'classical', 'Choral'),
('solo piano', 'classical', 'Solo Piano'),
('string quartet', 'classical', 'String Quartet'),
('minimalism', 'classical', 'Minimalism'),
('neo-classical', 'classical', 'Neo-Classical'),
('film score', 'classical', 'Film Score'),
('early music', 'classical', 'Early Music'),
('heavy metal', 'metal', 'Heavy Metal'),
('thrash metal', 'metal', 'Thrash Metal'),
('death metal', 'metal', 'Death Metal'),
('black metal', 'metal', 'Black Metal'),
('doom metal', 'metal', 'Doom Metal')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('power metal', 'metal', 'Power Metal'),
('progressive metal', 'metal', 'Progressive Metal'),
('metalcore', 'metal', 'Metalcore'),
('deathcore', 'metal', 'Deathcore'),
('nu metal', 'metal', 'Nu Metal'),
('symphonic metal', 'metal', 'Symphonic Metal'),
('folk metal', 'metal', 'Folk Metal'),
('industrial metal', 'metal', 'Industrial Metal'),
('groove metal', 'metal', 'Groove Metal'),
('sludge metal', 'metal', 'Sludge Metal'),
('post-metal', 'metal', 'Post-Metal'),
('melodic death metal', 'metal', 'Melodic Death Metal'),
('speed metal', 'metal', 'Speed Metal'),
('hardcore punk', 'punk', 'Hardcore Punk'),
('post-punk', 'punk', 'Post-Punk'),
('anarcho-punk', 'punk', 'Anarcho-Punk'),
('skate punk', 'punk', 'Skate Punk'),
('oi!', 'punk', 'Oi!'),
('crust punk', 'punk', 'Crust Punk'),
('garage punk', 'punk', 'Garage Punk'),
('punk rock', 'punk', 'Punk Rock'),
('street punk', 'punk', 'Street Punk'),
('ska punk', 'punk', 'Ska Punk'),
('riot grrrl', 'punk', 'Riot Grrrl'),
('queercore', 'punk', 'Queercore'),
('post-hardcore', 'punk', 'Post-Hardcore'),
('roots reggae', 'reggae', 'Roots Reggae'),
('dub', 'reggae', 'Dub'),
('rocksteady', 'reggae', 'Rocksteady'),
('ska', 'reggae', 'Ska'),
('reggae fusion', 'reggae', 'Reggae Fusion'),
('lovers rock', 'reggae', 'Lovers Rock'),
('digital reggae', 'reggae', 'Digital Reggae'),
('ragga', 'reggae', 'Ragga'),
('steppers', 'reggae', 'Steppers'),
('salsa', 'latin', 'Salsa'),
('bachata', 'latin', 'Bachata'),
('merengue', 'latin', 'Merengue'),
('reggaeton', 'latin', 'Reggaeton'),
('cumbia', 'latin', 'Cumbia'),
('tango', 'latin', 'Tango'),
('bolero', 'latin', 'Bolero'),
('latin rock', 'latin', 'Latin Rock'),
('son cubano', 'latin', 'Son Cubano'),
('bossa nova', 'latin', 'Bossa Nova'),
('samba', 'latin', 'Samba'),
('forró', 'latin', 'Forró'),
('chicha', 'latin', 'Chicha'),
('corridos', 'latin', 'Corridos'),
('mariachi', 'latin', 'Mariachi')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('soul', 'soul & funk', 'Soul'),
('funk', 'soul & funk', 'Funk'),
('motown', 'soul & funk', 'Motown'),
('psychedelic soul', 'soul & funk', 'Psychedelic Soul'),
('deep funk', 'soul & funk', 'Deep Funk'),
('p-funk', 'soul & funk', 'P-Funk'),
('disco funk', 'soul & funk', 'Disco Funk'),
('funk rock', 'soul & funk', 'Funk Rock'),
('northern soul', 'soul & funk', 'Northern Soul'),
('modern funk', 'soul & funk', 'Modern Funk'),
('traditional gospel', 'gospel', 'Traditional Gospel'),
('contemporary gospel', 'gospel', 'Contemporary Gospel'),
('southern gospel', 'gospel', 'Southern Gospel'),
('gospel choir', 'gospel', 'Gospel Choir'),
('urban gospel', 'gospel', 'Urban Gospel'),
('praise and worship', 'gospel', 'Praise and Worship'),
('spirituals', 'gospel', 'Spirituals'),
('afrobeat', 'world', 'Afrobeat'),
('afrobeats', 'world', 'Afrobeats'),
('highlife', 'world', 'Highlife'),
('mbalax', 'world', 'Mbalax'),
('raï', 'world', 'Raï'),
('gnawa', 'world', 'Gnawa'),
('qawwali', 'world', 'Qawwali'),
('klezmer', 'world', 'Klezmer'),
('flamenco', 'world', 'Flamenco'),
('fado', 'world', 'Fado'),
('kwaito', 'world', 'Kwaito'),
('gqom', 'world', 'Gqom'),
('celtic', 'world', 'Celtic'),
('balkan', 'world', 'Balkan'),
('bollywood', 'world', 'Bollywood'),
('mandopop', 'world', 'Mandopop'),
('arabesque', 'world', 'Arabesque'),
('anatolian rock', 'world', 'Anatolian Rock'),
('tv score', 'soundtrack', 'TV Score'),
('video game soundtrack', 'soundtrack', 'Video Game Soundtrack'),
('anime ost', 'soundtrack', 'Anime OST'),
('stage musical', 'soundtrack', 'Stage Musical'),
('orchestral soundtrack', 'soundtrack', 'Orchestral Soundtrack'),
('synth score', 'soundtrack', 'Synth Score'),
('trailer music', 'soundtrack', 'Trailer Music'),
('noise', 'experimental', 'Noise'),
('avant-garde', 'experimental', 'Avant-Garde'),
('electroacoustic', 'experimental', 'Electroacoustic'),
('musique concrète', 'experimental', 'Musique Concrète'),
('drone', 'experimental', 'Drone'),
('sound art', 'experimental', 'Sound Art'),
('free improvisation', 'experimental', 'Free Improvisation'),
('microsound', 'experimental', 'Microsound')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('ambient experimental', 'experimental', 'Ambient Experimental'),
('dark ambient', 'ambient', 'Dark Ambient'),
('space ambient', 'ambient', 'Space Ambient'),
('drone ambient', 'ambient', 'Drone Ambient'),
('ambient dub', 'ambient', 'Ambient Dub'),
('new age', 'ambient', 'New Age'),
('meditation', 'ambient', 'Meditation'),
('nature sounds', 'ambient', 'Nature Sounds'),
('field recordings', 'ambient', 'Field Recordings'),
('acoustic singer-songwriter', 'singer-songwriter', 'Acoustic Singer-Songwriter'),
('indie singer-songwriter', 'singer-songwriter', 'Indie Singer-Songwriter'),
('folk singer-songwriter', 'singer-songwriter', 'Folk Singer-Songwriter'),
('pop singer-songwriter', 'singer-songwriter', 'Pop Singer-Songwriter'),
('alt singer-songwriter', 'singer-songwriter', 'Alt Singer-Songwriter'),
('lullabies', 'children', 'Lullabies'),
('kids pop', 'children', 'Kids Pop'),
('nursery rhymes', 'children', 'Nursery Rhymes'),
('educational', 'children', 'Educational'),
('story songs', 'children', 'Story Songs'),
('comedy music', 'comedy', 'Comedy Music'),
('stand-up', 'comedy', 'Stand-up'),
('sketch comedy', 'comedy', 'Sketch Comedy'),
('parody', 'comedy', 'Parody'),
('satire', 'comedy', 'Satire'),
('poetry', 'spoken word', 'Poetry'),
('audiobook', 'spoken word', 'Audiobook'),
('lecture', 'spoken word', 'Lecture'),
('storytelling', 'spoken word', 'Storytelling'),
('podcast', 'spoken word', 'Podcast')
ON CONFLICT (tag) DO NOTHING;

-- Level 2 (1289 entries)
INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('ambient house', 'house', 'Ambient House'),
('melodic house', 'house', 'Melodic House'),
('lo-fi house', 'house', 'Lo-Fi House'),
('acoustic house', 'house', 'Acoustic House'),
('organic house', 'house', 'Organic House'),
('downtempo house', 'house', 'Downtempo House'),
('hard house', 'house', 'Hard House'),
('futuristic house', 'house', 'Futuristic House'),
('classic house', 'house', 'Classic House'),
('dark house', 'house', 'Dark House'),
('emotive house', 'house', 'Emotive House'),
('nigerian house', 'house', 'Nigerian House'),
('french house', 'house', 'French House'),
('mexican house', 'house', 'Mexican House'),
('german house', 'house', 'German House'),
('indian house', 'house', 'Indian House'),
('japanese house', 'house', 'Japanese House'),
('balkan house', 'house', 'Balkan House'),
('ghanaian house', 'house', 'Ghanaian House'),
('70s house', 'house', '70s House'),
('80s house', 'house', '80s House'),
('90s house', 'house', '90s House'),
('2000s house', 'house', '2000s House'),
('2010s house', 'house', '2010s House'),
('2020s house', 'house', '2020s House'),
('house / jazz fusion', 'house', 'House / Jazz Fusion'),
('house / funk fusion', 'house', 'House / Funk Fusion'),
('house / rock fusion', 'house', 'House / Rock Fusion'),
('house / classical fusion', 'house', 'House / Classical Fusion'),
('house / soul fusion', 'house', 'House / Soul Fusion'),
('bright techno', 'techno', 'Bright Techno'),
('lo-fi techno', 'techno', 'Lo-Fi Techno'),
('emotive techno', 'techno', 'Emotive Techno'),
('acoustic techno', 'techno', 'Acoustic Techno'),
('modern techno', 'techno', 'Modern Techno'),
('downtempo techno', 'techno', 'Downtempo Techno'),
('melodic techno', 'techno', 'Melodic Techno'),
('electric techno', 'techno', 'Electric Techno'),
('experimental techno', 'techno', 'Experimental Techno'),
('progressive techno', 'techno', 'Progressive Techno'),
('deep techno', 'techno', 'Deep Techno'),
('ghanaian techno', 'techno', 'Ghanaian Techno'),
('uk techno', 'techno', 'UK Techno'),
('balkan techno', 'techno', 'Balkan Techno'),
('mexican techno', 'techno', 'Mexican Techno'),
('nordic techno', 'techno', 'Nordic Techno'),
('caribbean techno', 'techno', 'Caribbean Techno'),
('us techno', 'techno', 'US Techno'),
('south african techno', 'techno', 'South African Techno'),
('70s techno', 'techno', '70s Techno')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('80s techno', 'techno', '80s Techno'),
('90s techno', 'techno', '90s Techno'),
('2000s techno', 'techno', '2000s Techno'),
('2010s techno', 'techno', '2010s Techno'),
('2020s techno', 'techno', '2020s Techno'),
('techno / ambient fusion', 'techno', 'Techno / Ambient Fusion'),
('techno / jazz fusion', 'techno', 'Techno / Jazz Fusion'),
('techno / pop fusion', 'techno', 'Techno / Pop Fusion'),
('techno / hip hop fusion', 'techno', 'Techno / Hip Hop Fusion'),
('techno / rock fusion', 'techno', 'Techno / Rock Fusion'),
('progressive trance', 'trance', 'Progressive Trance'),
('chill trance', 'trance', 'Chill Trance'),
('underground trance', 'trance', 'Underground Trance'),
('classic trance', 'trance', 'Classic Trance'),
('futuristic trance', 'trance', 'Futuristic Trance'),
('orchestral trance', 'trance', 'Orchestral Trance'),
('downtempo trance', 'trance', 'Downtempo Trance'),
('experimental trance', 'trance', 'Experimental Trance'),
('retro trance', 'trance', 'Retro Trance'),
('modern trance', 'trance', 'Modern Trance'),
('minimal trance', 'trance', 'Minimal Trance'),
('lo-fi trance', 'trance', 'Lo-Fi Trance'),
('turkish trance', 'trance', 'Turkish Trance'),
('balkan trance', 'trance', 'Balkan Trance'),
('nigerian trance', 'trance', 'Nigerian Trance'),
('nordic trance', 'trance', 'Nordic Trance'),
('uk trance', 'trance', 'UK Trance'),
('ghanaian trance', 'trance', 'Ghanaian Trance'),
('arabic trance', 'trance', 'Arabic Trance'),
('cuban trance', 'trance', 'Cuban Trance'),
('70s trance', 'trance', '70s Trance'),
('80s trance', 'trance', '80s Trance'),
('90s trance', 'trance', '90s Trance'),
('2000s trance', 'trance', '2000s Trance'),
('2010s trance', 'trance', '2010s Trance'),
('2020s trance', 'trance', '2020s Trance'),
('trance / jazz fusion', 'trance', 'Trance / Jazz Fusion'),
('trance / rock fusion', 'trance', 'Trance / Rock Fusion'),
('trance / pop fusion', 'trance', 'Trance / Pop Fusion'),
('trance / latin fusion', 'trance', 'Trance / Latin Fusion'),
('trance / soul fusion', 'trance', 'Trance / Soul Fusion'),
('organic drum and bass', 'drum and bass', 'Organic Drum and Bass'),
('progressive drum and bass', 'drum and bass', 'Progressive Drum and Bass'),
('bright drum and bass', 'drum and bass', 'Bright Drum and Bass'),
('cinematic drum and bass', 'drum and bass', 'Cinematic Drum and Bass'),
('electric drum and bass', 'drum and bass', 'Electric Drum and Bass'),
('vintage drum and bass', 'drum and bass', 'Vintage Drum and Bass'),
('ambient drum and bass', 'drum and bass', 'Ambient Drum and Bass'),
('lo-fi drum and bass', 'drum and bass', 'Lo-Fi Drum and Bass'),
('futuristic drum and bass', 'drum and bass', 'Futuristic Drum and Bass')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('atmospheric drum and bass', 'drum and bass', 'Atmospheric Drum and Bass'),
('orchestral drum and bass', 'drum and bass', 'Orchestral Drum and Bass'),
('hard drum and bass', 'drum and bass', 'Hard Drum and Bass'),
('nigerian drum and bass', 'drum and bass', 'Nigerian Drum and Bass'),
('arabic drum and bass', 'drum and bass', 'Arabic Drum and Bass'),
('ghanaian drum and bass', 'drum and bass', 'Ghanaian Drum and Bass'),
('indian drum and bass', 'drum and bass', 'Indian Drum and Bass'),
('andean drum and bass', 'drum and bass', 'Andean Drum and Bass'),
('cuban drum and bass', 'drum and bass', 'Cuban Drum and Bass'),
('french drum and bass', 'drum and bass', 'French Drum and Bass'),
('german drum and bass', 'drum and bass', 'German Drum and Bass'),
('70s drum and bass', 'drum and bass', '70s Drum and Bass'),
('80s drum and bass', 'drum and bass', '80s Drum and Bass'),
('90s drum and bass', 'drum and bass', '90s Drum and Bass'),
('2000s drum and bass', 'drum and bass', '2000s Drum and Bass'),
('2010s drum and bass', 'drum and bass', '2010s Drum and Bass'),
('2020s drum and bass', 'drum and bass', '2020s Drum and Bass'),
('drum and bass / ambient fusion', 'drum and bass', 'Drum and Bass / Ambient Fusion'),
('drum and bass / jazz fusion', 'drum and bass', 'Drum and Bass / Jazz Fusion'),
('drum and bass / pop fusion', 'drum and bass', 'Drum and Bass / Pop Fusion'),
('drum and bass / soul fusion', 'drum and bass', 'Drum and Bass / Soul Fusion'),
('drum and bass / hip hop fusion', 'drum and bass', 'Drum and Bass / Hip Hop Fusion'),
('minimal dubstep', 'dubstep', 'Minimal Dubstep'),
('emotive dubstep', 'dubstep', 'Emotive Dubstep'),
('retro dubstep', 'dubstep', 'Retro Dubstep'),
('bright dubstep', 'dubstep', 'Bright Dubstep'),
('acoustic dubstep', 'dubstep', 'Acoustic Dubstep'),
('organic dubstep', 'dubstep', 'Organic Dubstep'),
('downtempo dubstep', 'dubstep', 'Downtempo Dubstep'),
('modern dubstep', 'dubstep', 'Modern Dubstep'),
('futuristic dubstep', 'dubstep', 'Futuristic Dubstep'),
('ambient dubstep', 'dubstep', 'Ambient Dubstep'),
('experimental dubstep', 'dubstep', 'Experimental Dubstep'),
('underground dubstep', 'dubstep', 'Underground Dubstep'),
('ghanaian dubstep', 'dubstep', 'Ghanaian Dubstep'),
('indian dubstep', 'dubstep', 'Indian Dubstep'),
('korean dubstep', 'dubstep', 'Korean Dubstep'),
('turkish dubstep', 'dubstep', 'Turkish Dubstep'),
('japanese dubstep', 'dubstep', 'Japanese Dubstep'),
('nigerian dubstep', 'dubstep', 'Nigerian Dubstep'),
('cuban dubstep', 'dubstep', 'Cuban Dubstep'),
('uk dubstep', 'dubstep', 'UK Dubstep'),
('70s dubstep', 'dubstep', '70s Dubstep'),
('80s dubstep', 'dubstep', '80s Dubstep'),
('90s dubstep', 'dubstep', '90s Dubstep'),
('2000s dubstep', 'dubstep', '2000s Dubstep'),
('2010s dubstep', 'dubstep', '2010s Dubstep'),
('2020s dubstep', 'dubstep', '2020s Dubstep'),
('dubstep / jazz fusion', 'dubstep', 'Dubstep / Jazz Fusion'),
('dubstep / funk fusion', 'dubstep', 'Dubstep / Funk Fusion')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('dubstep / hip hop fusion', 'dubstep', 'Dubstep / Hip Hop Fusion'),
('dubstep / ambient fusion', 'dubstep', 'Dubstep / Ambient Fusion'),
('dubstep / latin fusion', 'dubstep', 'Dubstep / Latin Fusion'),
('cinematic garage', 'garage', 'Cinematic Garage'),
('classic garage', 'garage', 'Classic Garage'),
('dark garage', 'garage', 'Dark Garage'),
('downtempo garage', 'garage', 'Downtempo Garage'),
('vintage garage', 'garage', 'Vintage Garage'),
('deep garage', 'garage', 'Deep Garage'),
('modern garage', 'garage', 'Modern Garage'),
('orchestral garage', 'garage', 'Orchestral Garage'),
('lo-fi garage', 'garage', 'Lo-Fi Garage'),
('emotive garage', 'garage', 'Emotive Garage'),
('retro garage', 'garage', 'Retro Garage'),
('chill garage', 'garage', 'Chill Garage'),
('brazilian garage', 'garage', 'Brazilian Garage'),
('french garage', 'garage', 'French Garage'),
('mexican garage', 'garage', 'Mexican Garage'),
('arabic garage', 'garage', 'Arabic Garage'),
('spanish garage', 'garage', 'Spanish Garage'),
('cuban garage', 'garage', 'Cuban Garage'),
('indian garage', 'garage', 'Indian Garage'),
('german garage', 'garage', 'German Garage'),
('70s garage', 'garage', '70s Garage'),
('80s garage', 'garage', '80s Garage'),
('90s garage', 'garage', '90s Garage'),
('2000s garage', 'garage', '2000s Garage'),
('2010s garage', 'garage', '2010s Garage'),
('2020s garage', 'garage', '2020s Garage'),
('garage / ambient fusion', 'garage', 'Garage / Ambient Fusion'),
('garage / funk fusion', 'garage', 'Garage / Funk Fusion'),
('garage / hip hop fusion', 'garage', 'Garage / Hip Hop Fusion'),
('garage / classical fusion', 'garage', 'Garage / Classical Fusion'),
('garage / rock fusion', 'garage', 'Garage / Rock Fusion'),
('retro idm', 'idm', 'Retro IDM'),
('deep idm', 'idm', 'Deep IDM'),
('underground idm', 'idm', 'Underground IDM'),
('ambient idm', 'idm', 'Ambient IDM'),
('downtempo idm', 'idm', 'Downtempo IDM'),
('chill idm', 'idm', 'Chill IDM'),
('hard idm', 'idm', 'Hard IDM'),
('experimental idm', 'idm', 'Experimental IDM'),
('electric idm', 'idm', 'Electric IDM'),
('futuristic idm', 'idm', 'Futuristic IDM'),
('organic idm', 'idm', 'Organic IDM'),
('uplifting idm', 'idm', 'Uplifting IDM'),
('caribbean idm', 'idm', 'Caribbean IDM'),
('brazilian idm', 'idm', 'Brazilian IDM'),
('arabic idm', 'idm', 'Arabic IDM'),
('german idm', 'idm', 'German IDM')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('mexican idm', 'idm', 'Mexican IDM'),
('ghanaian idm', 'idm', 'Ghanaian IDM'),
('french idm', 'idm', 'French IDM'),
('japanese idm', 'idm', 'Japanese IDM'),
('70s idm', 'idm', '70s IDM'),
('80s idm', 'idm', '80s IDM'),
('90s idm', 'idm', '90s IDM'),
('2000s idm', 'idm', '2000s IDM'),
('2010s idm', 'idm', '2010s IDM'),
('2020s idm', 'idm', '2020s IDM'),
('idm / jazz fusion', 'idm', 'IDM / Jazz Fusion'),
('idm / funk fusion', 'idm', 'IDM / Funk Fusion'),
('idm / hip hop fusion', 'idm', 'IDM / Hip Hop Fusion'),
('idm / soul fusion', 'idm', 'IDM / Soul Fusion'),
('idm / rock fusion', 'idm', 'IDM / Rock Fusion'),
('cinematic breakbeat', 'breakbeat', 'Cinematic Breakbeat'),
('experimental breakbeat', 'breakbeat', 'Experimental Breakbeat'),
('retro breakbeat', 'breakbeat', 'Retro Breakbeat'),
('ambient breakbeat', 'breakbeat', 'Ambient Breakbeat'),
('bright breakbeat', 'breakbeat', 'Bright Breakbeat'),
('chill breakbeat', 'breakbeat', 'Chill Breakbeat'),
('progressive breakbeat', 'breakbeat', 'Progressive Breakbeat'),
('acoustic breakbeat', 'breakbeat', 'Acoustic Breakbeat'),
('classic breakbeat', 'breakbeat', 'Classic Breakbeat'),
('hard breakbeat', 'breakbeat', 'Hard Breakbeat'),
('electric breakbeat', 'breakbeat', 'Electric Breakbeat'),
('organic breakbeat', 'breakbeat', 'Organic Breakbeat'),
('nigerian breakbeat', 'breakbeat', 'Nigerian Breakbeat'),
('caribbean breakbeat', 'breakbeat', 'Caribbean Breakbeat'),
('spanish breakbeat', 'breakbeat', 'Spanish Breakbeat'),
('japanese breakbeat', 'breakbeat', 'Japanese Breakbeat'),
('turkish breakbeat', 'breakbeat', 'Turkish Breakbeat'),
('cuban breakbeat', 'breakbeat', 'Cuban Breakbeat'),
('mexican breakbeat', 'breakbeat', 'Mexican Breakbeat'),
('korean breakbeat', 'breakbeat', 'Korean Breakbeat'),
('70s breakbeat', 'breakbeat', '70s Breakbeat'),
('80s breakbeat', 'breakbeat', '80s Breakbeat'),
('90s breakbeat', 'breakbeat', '90s Breakbeat'),
('2000s breakbeat', 'breakbeat', '2000s Breakbeat'),
('2010s breakbeat', 'breakbeat', '2010s Breakbeat'),
('2020s breakbeat', 'breakbeat', '2020s Breakbeat'),
('breakbeat / hip hop fusion', 'breakbeat', 'Breakbeat / Hip Hop Fusion'),
('breakbeat / ambient fusion', 'breakbeat', 'Breakbeat / Ambient Fusion'),
('breakbeat / latin fusion', 'breakbeat', 'Breakbeat / Latin Fusion'),
('breakbeat / classical fusion', 'breakbeat', 'Breakbeat / Classical Fusion'),
('breakbeat / jazz fusion', 'breakbeat', 'Breakbeat / Jazz Fusion'),
('cinematic alternative rock', 'alternative rock', 'Cinematic Alternative Rock'),
('vintage alternative rock', 'alternative rock', 'Vintage Alternative Rock'),
('dark alternative rock', 'alternative rock', 'Dark Alternative Rock'),
('hard alternative rock', 'alternative rock', 'Hard Alternative Rock')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('organic alternative rock', 'alternative rock', 'Organic Alternative Rock'),
('modern alternative rock', 'alternative rock', 'Modern Alternative Rock'),
('emotive alternative rock', 'alternative rock', 'Emotive Alternative Rock'),
('underground alternative rock', 'alternative rock', 'Underground Alternative Rock'),
('minimal alternative rock', 'alternative rock', 'Minimal Alternative Rock'),
('classic alternative rock', 'alternative rock', 'Classic Alternative Rock'),
('ambient alternative rock', 'alternative rock', 'Ambient Alternative Rock'),
('chill alternative rock', 'alternative rock', 'Chill Alternative Rock'),
('us alternative rock', 'alternative rock', 'US Alternative Rock'),
('spanish alternative rock', 'alternative rock', 'Spanish Alternative Rock'),
('nigerian alternative rock', 'alternative rock', 'Nigerian Alternative Rock'),
('mexican alternative rock', 'alternative rock', 'Mexican Alternative Rock'),
('south african alternative rock', 'alternative rock', 'South African Alternative Rock'),
('german alternative rock', 'alternative rock', 'German Alternative Rock'),
('ghanaian alternative rock', 'alternative rock', 'Ghanaian Alternative Rock'),
('turkish alternative rock', 'alternative rock', 'Turkish Alternative Rock'),
('70s alternative rock', 'alternative rock', '70s Alternative Rock'),
('80s alternative rock', 'alternative rock', '80s Alternative Rock'),
('90s alternative rock', 'alternative rock', '90s Alternative Rock'),
('2000s alternative rock', 'alternative rock', '2000s Alternative Rock'),
('2010s alternative rock', 'alternative rock', '2010s Alternative Rock'),
('2020s alternative rock', 'alternative rock', '2020s Alternative Rock'),
('alternative rock / latin fusion', 'alternative rock', 'Alternative Rock / Latin Fusion'),
('alternative rock / pop fusion', 'alternative rock', 'Alternative Rock / Pop Fusion'),
('alternative rock / hip hop fusion', 'alternative rock', 'Alternative Rock / Hip Hop Fusion'),
('alternative rock / funk fusion', 'alternative rock', 'Alternative Rock / Funk Fusion'),
('ambient indie rock', 'indie rock', 'Ambient Indie Rock'),
('dark indie rock', 'indie rock', 'Dark Indie Rock'),
('melodic indie rock', 'indie rock', 'Melodic Indie Rock'),
('hard indie rock', 'indie rock', 'Hard Indie Rock'),
('chill indie rock', 'indie rock', 'Chill Indie Rock'),
('downtempo indie rock', 'indie rock', 'Downtempo Indie Rock'),
('electric indie rock', 'indie rock', 'Electric Indie Rock'),
('retro indie rock', 'indie rock', 'Retro Indie Rock'),
('emotive indie rock', 'indie rock', 'Emotive Indie Rock'),
('classic indie rock', 'indie rock', 'Classic Indie Rock'),
('organic indie rock', 'indie rock', 'Organic Indie Rock'),
('bright indie rock', 'indie rock', 'Bright Indie Rock'),
('mexican indie rock', 'indie rock', 'Mexican Indie Rock'),
('japanese indie rock', 'indie rock', 'Japanese Indie Rock'),
('brazilian indie rock', 'indie rock', 'Brazilian Indie Rock'),
('french indie rock', 'indie rock', 'French Indie Rock'),
('balkan indie rock', 'indie rock', 'Balkan Indie Rock'),
('nigerian indie rock', 'indie rock', 'Nigerian Indie Rock'),
('german indie rock', 'indie rock', 'German Indie Rock'),
('arabic indie rock', 'indie rock', 'Arabic Indie Rock'),
('70s indie rock', 'indie rock', '70s Indie Rock'),
('80s indie rock', 'indie rock', '80s Indie Rock'),
('90s indie rock', 'indie rock', '90s Indie Rock'),
('2000s indie rock', 'indie rock', '2000s Indie Rock')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('2010s indie rock', 'indie rock', '2010s Indie Rock'),
('2020s indie rock', 'indie rock', '2020s Indie Rock'),
('indie rock / funk fusion', 'indie rock', 'Indie Rock / Funk Fusion'),
('indie rock / jazz fusion', 'indie rock', 'Indie Rock / Jazz Fusion'),
('indie rock / hip hop fusion', 'indie rock', 'Indie Rock / Hip Hop Fusion'),
('indie rock / classical fusion', 'indie rock', 'Indie Rock / Classical Fusion'),
('indie rock / latin fusion', 'indie rock', 'Indie Rock / Latin Fusion'),
('dark hard rock', 'hard rock', 'Dark Hard Rock'),
('orchestral hard rock', 'hard rock', 'Orchestral Hard Rock'),
('bright hard rock', 'hard rock', 'Bright Hard Rock'),
('atmospheric hard rock', 'hard rock', 'Atmospheric Hard Rock'),
('vintage hard rock', 'hard rock', 'Vintage Hard Rock'),
('melodic hard rock', 'hard rock', 'Melodic Hard Rock'),
('futuristic hard rock', 'hard rock', 'Futuristic Hard Rock'),
('downtempo hard rock', 'hard rock', 'Downtempo Hard Rock'),
('experimental hard rock', 'hard rock', 'Experimental Hard Rock'),
('acoustic hard rock', 'hard rock', 'Acoustic Hard Rock'),
('cinematic hard rock', 'hard rock', 'Cinematic Hard Rock'),
('deep hard rock', 'hard rock', 'Deep Hard Rock'),
('andean hard rock', 'hard rock', 'Andean Hard Rock'),
('balkan hard rock', 'hard rock', 'Balkan Hard Rock'),
('uk hard rock', 'hard rock', 'UK Hard Rock'),
('cuban hard rock', 'hard rock', 'Cuban Hard Rock'),
('caribbean hard rock', 'hard rock', 'Caribbean Hard Rock'),
('french hard rock', 'hard rock', 'French Hard Rock'),
('japanese hard rock', 'hard rock', 'Japanese Hard Rock'),
('south african hard rock', 'hard rock', 'South African Hard Rock'),
('70s hard rock', 'hard rock', '70s Hard Rock'),
('80s hard rock', 'hard rock', '80s Hard Rock'),
('90s hard rock', 'hard rock', '90s Hard Rock'),
('2000s hard rock', 'hard rock', '2000s Hard Rock'),
('2010s hard rock', 'hard rock', '2010s Hard Rock'),
('2020s hard rock', 'hard rock', '2020s Hard Rock'),
('hard rock / hip hop fusion', 'hard rock', 'Hard Rock / Hip Hop Fusion'),
('hard rock / latin fusion', 'hard rock', 'Hard Rock / Latin Fusion'),
('hard rock / ambient fusion', 'hard rock', 'Hard Rock / Ambient Fusion'),
('hard rock / jazz fusion', 'hard rock', 'Hard Rock / Jazz Fusion'),
('hard rock / soul fusion', 'hard rock', 'Hard Rock / Soul Fusion'),
('organic progressive rock', 'progressive rock', 'Organic Progressive Rock'),
('modern progressive rock', 'progressive rock', 'Modern Progressive Rock'),
('classic progressive rock', 'progressive rock', 'Classic Progressive Rock'),
('downtempo progressive rock', 'progressive rock', 'Downtempo Progressive Rock'),
('cinematic progressive rock', 'progressive rock', 'Cinematic Progressive Rock'),
('deep progressive rock', 'progressive rock', 'Deep Progressive Rock'),
('atmospheric progressive rock', 'progressive rock', 'Atmospheric Progressive Rock'),
('chill progressive rock', 'progressive rock', 'Chill Progressive Rock'),
('dark progressive rock', 'progressive rock', 'Dark Progressive Rock'),
('lo-fi progressive rock', 'progressive rock', 'Lo-Fi Progressive Rock'),
('bright progressive rock', 'progressive rock', 'Bright Progressive Rock'),
('retro progressive rock', 'progressive rock', 'Retro Progressive Rock')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('mexican progressive rock', 'progressive rock', 'Mexican Progressive Rock'),
('german progressive rock', 'progressive rock', 'German Progressive Rock'),
('japanese progressive rock', 'progressive rock', 'Japanese Progressive Rock'),
('cuban progressive rock', 'progressive rock', 'Cuban Progressive Rock'),
('brazilian progressive rock', 'progressive rock', 'Brazilian Progressive Rock'),
('french progressive rock', 'progressive rock', 'French Progressive Rock'),
('nigerian progressive rock', 'progressive rock', 'Nigerian Progressive Rock'),
('turkish progressive rock', 'progressive rock', 'Turkish Progressive Rock'),
('70s progressive rock', 'progressive rock', '70s Progressive Rock'),
('80s progressive rock', 'progressive rock', '80s Progressive Rock'),
('90s progressive rock', 'progressive rock', '90s Progressive Rock'),
('2000s progressive rock', 'progressive rock', '2000s Progressive Rock'),
('2010s progressive rock', 'progressive rock', '2010s Progressive Rock'),
('2020s progressive rock', 'progressive rock', '2020s Progressive Rock'),
('progressive rock / jazz fusion', 'progressive rock', 'Progressive Rock / Jazz Fusion'),
('progressive rock / latin fusion', 'progressive rock', 'Progressive Rock / Latin Fusion'),
('progressive rock / classical fusion', 'progressive rock', 'Progressive Rock / Classical Fusion'),
('progressive rock / hip hop fusion', 'progressive rock', 'Progressive Rock / Hip Hop Fusion'),
('downtempo psychedelic rock', 'psychedelic rock', 'Downtempo Psychedelic Rock'),
('experimental psychedelic rock', 'psychedelic rock', 'Experimental Psychedelic Rock'),
('chill psychedelic rock', 'psychedelic rock', 'Chill Psychedelic Rock'),
('ambient psychedelic rock', 'psychedelic rock', 'Ambient Psychedelic Rock'),
('uplifting psychedelic rock', 'psychedelic rock', 'Uplifting Psychedelic Rock'),
('orchestral psychedelic rock', 'psychedelic rock', 'Orchestral Psychedelic Rock'),
('deep psychedelic rock', 'psychedelic rock', 'Deep Psychedelic Rock'),
('vintage psychedelic rock', 'psychedelic rock', 'Vintage Psychedelic Rock'),
('melodic psychedelic rock', 'psychedelic rock', 'Melodic Psychedelic Rock'),
('atmospheric psychedelic rock', 'psychedelic rock', 'Atmospheric Psychedelic Rock'),
('electric psychedelic rock', 'psychedelic rock', 'Electric Psychedelic Rock'),
('hard psychedelic rock', 'psychedelic rock', 'Hard Psychedelic Rock'),
('korean psychedelic rock', 'psychedelic rock', 'Korean Psychedelic Rock'),
('andean psychedelic rock', 'psychedelic rock', 'Andean Psychedelic Rock'),
('caribbean psychedelic rock', 'psychedelic rock', 'Caribbean Psychedelic Rock'),
('turkish psychedelic rock', 'psychedelic rock', 'Turkish Psychedelic Rock'),
('us psychedelic rock', 'psychedelic rock', 'US Psychedelic Rock'),
('brazilian psychedelic rock', 'psychedelic rock', 'Brazilian Psychedelic Rock'),
('balkan psychedelic rock', 'psychedelic rock', 'Balkan Psychedelic Rock'),
('ghanaian psychedelic rock', 'psychedelic rock', 'Ghanaian Psychedelic Rock'),
('70s psychedelic rock', 'psychedelic rock', '70s Psychedelic Rock'),
('80s psychedelic rock', 'psychedelic rock', '80s Psychedelic Rock'),
('90s psychedelic rock', 'psychedelic rock', '90s Psychedelic Rock'),
('2000s psychedelic rock', 'psychedelic rock', '2000s Psychedelic Rock'),
('2010s psychedelic rock', 'psychedelic rock', '2010s Psychedelic Rock'),
('2020s psychedelic rock', 'psychedelic rock', '2020s Psychedelic Rock'),
('psychedelic rock / ambient fusion', 'psychedelic rock', 'Psychedelic Rock / Ambient Fusion'),
('psychedelic rock / pop fusion', 'psychedelic rock', 'Psychedelic Rock / Pop Fusion'),
('psychedelic rock / latin fusion', 'psychedelic rock', 'Psychedelic Rock / Latin Fusion'),
('psychedelic rock / funk fusion', 'psychedelic rock', 'Psychedelic Rock / Funk Fusion'),
('psychedelic rock / jazz fusion', 'psychedelic rock', 'Psychedelic Rock / Jazz Fusion'),
('bright trap', 'trap', 'Bright Trap')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('experimental trap', 'trap', 'Experimental Trap'),
('lo-fi trap', 'trap', 'Lo-Fi Trap'),
('deep trap', 'trap', 'Deep Trap'),
('emotive trap', 'trap', 'Emotive Trap'),
('acoustic trap', 'trap', 'Acoustic Trap'),
('progressive trap', 'trap', 'Progressive Trap'),
('hard trap', 'trap', 'Hard Trap'),
('classic trap', 'trap', 'Classic Trap'),
('modern trap', 'trap', 'Modern Trap'),
('dark trap', 'trap', 'Dark Trap'),
('chill trap', 'trap', 'Chill Trap'),
('german trap', 'trap', 'German Trap'),
('caribbean trap', 'trap', 'Caribbean Trap'),
('ghanaian trap', 'trap', 'Ghanaian Trap'),
('japanese trap', 'trap', 'Japanese Trap'),
('us trap', 'trap', 'US Trap'),
('korean trap', 'trap', 'Korean Trap'),
('cuban trap', 'trap', 'Cuban Trap'),
('turkish trap', 'trap', 'Turkish Trap'),
('70s trap', 'trap', '70s Trap'),
('80s trap', 'trap', '80s Trap'),
('90s trap', 'trap', '90s Trap'),
('2000s trap', 'trap', '2000s Trap'),
('2010s trap', 'trap', '2010s Trap'),
('2020s trap', 'trap', '2020s Trap'),
('trap / latin fusion', 'trap', 'Trap / Latin Fusion'),
('trap / jazz fusion', 'trap', 'Trap / Jazz Fusion'),
('trap / rock fusion', 'trap', 'Trap / Rock Fusion'),
('trap / soul fusion', 'trap', 'Trap / Soul Fusion'),
('trap / ambient fusion', 'trap', 'Trap / Ambient Fusion'),
('bright drill', 'drill', 'Bright Drill'),
('chill drill', 'drill', 'Chill Drill'),
('emotive drill', 'drill', 'Emotive Drill'),
('cinematic drill', 'drill', 'Cinematic Drill'),
('experimental drill', 'drill', 'Experimental Drill'),
('dark drill', 'drill', 'Dark Drill'),
('acoustic drill', 'drill', 'Acoustic Drill'),
('futuristic drill', 'drill', 'Futuristic Drill'),
('deep drill', 'drill', 'Deep Drill'),
('atmospheric drill', 'drill', 'Atmospheric Drill'),
('uplifting drill', 'drill', 'Uplifting Drill'),
('downtempo drill', 'drill', 'Downtempo Drill'),
('spanish drill', 'drill', 'Spanish Drill'),
('brazilian drill', 'drill', 'Brazilian Drill'),
('german drill', 'drill', 'German Drill'),
('japanese drill', 'drill', 'Japanese Drill'),
('french drill', 'drill', 'French Drill'),
('mexican drill', 'drill', 'Mexican Drill'),
('andean drill', 'drill', 'Andean Drill'),
('south african drill', 'drill', 'South African Drill')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('70s drill', 'drill', '70s Drill'),
('80s drill', 'drill', '80s Drill'),
('90s drill', 'drill', '90s Drill'),
('2000s drill', 'drill', '2000s Drill'),
('2010s drill', 'drill', '2010s Drill'),
('2020s drill', 'drill', '2020s Drill'),
('drill / funk fusion', 'drill', 'Drill / Funk Fusion'),
('drill / classical fusion', 'drill', 'Drill / Classical Fusion'),
('drill / soul fusion', 'drill', 'Drill / Soul Fusion'),
('drill / latin fusion', 'drill', 'Drill / Latin Fusion'),
('drill / ambient fusion', 'drill', 'Drill / Ambient Fusion'),
('experimental boom bap', 'boom bap', 'Experimental Boom Bap'),
('classic boom bap', 'boom bap', 'Classic Boom Bap'),
('deep boom bap', 'boom bap', 'Deep Boom Bap'),
('modern boom bap', 'boom bap', 'Modern Boom Bap'),
('ambient boom bap', 'boom bap', 'Ambient Boom Bap'),
('minimal boom bap', 'boom bap', 'Minimal Boom Bap'),
('underground boom bap', 'boom bap', 'Underground Boom Bap'),
('vintage boom bap', 'boom bap', 'Vintage Boom Bap'),
('hard boom bap', 'boom bap', 'Hard Boom Bap'),
('downtempo boom bap', 'boom bap', 'Downtempo Boom Bap'),
('orchestral boom bap', 'boom bap', 'Orchestral Boom Bap'),
('dark boom bap', 'boom bap', 'Dark Boom Bap'),
('nordic boom bap', 'boom bap', 'Nordic Boom Bap'),
('balkan boom bap', 'boom bap', 'Balkan Boom Bap'),
('german boom bap', 'boom bap', 'German Boom Bap'),
('ghanaian boom bap', 'boom bap', 'Ghanaian Boom Bap'),
('mexican boom bap', 'boom bap', 'Mexican Boom Bap'),
('spanish boom bap', 'boom bap', 'Spanish Boom Bap'),
('us boom bap', 'boom bap', 'US Boom Bap'),
('japanese boom bap', 'boom bap', 'Japanese Boom Bap'),
('70s boom bap', 'boom bap', '70s Boom Bap'),
('80s boom bap', 'boom bap', '80s Boom Bap'),
('90s boom bap', 'boom bap', '90s Boom Bap'),
('2000s boom bap', 'boom bap', '2000s Boom Bap'),
('2010s boom bap', 'boom bap', '2010s Boom Bap'),
('2020s boom bap', 'boom bap', '2020s Boom Bap'),
('boom bap / jazz fusion', 'boom bap', 'Boom Bap / Jazz Fusion'),
('boom bap / pop fusion', 'boom bap', 'Boom Bap / Pop Fusion'),
('boom bap / latin fusion', 'boom bap', 'Boom Bap / Latin Fusion'),
('boom bap / soul fusion', 'boom bap', 'Boom Bap / Soul Fusion'),
('boom bap / hip hop fusion', 'boom bap', 'Boom Bap / Hip Hop Fusion'),
('chill lo-fi hip hop', 'lo-fi hip hop', 'Chill Lo-Fi Hip Hop'),
('hard lo-fi hip hop', 'lo-fi hip hop', 'Hard Lo-Fi Hip Hop'),
('uplifting lo-fi hip hop', 'lo-fi hip hop', 'Uplifting Lo-Fi Hip Hop'),
('orchestral lo-fi hip hop', 'lo-fi hip hop', 'Orchestral Lo-Fi Hip Hop'),
('retro lo-fi hip hop', 'lo-fi hip hop', 'Retro Lo-Fi Hip Hop'),
('modern lo-fi hip hop', 'lo-fi hip hop', 'Modern Lo-Fi Hip Hop'),
('bright lo-fi hip hop', 'lo-fi hip hop', 'Bright Lo-Fi Hip Hop'),
('futuristic lo-fi hip hop', 'lo-fi hip hop', 'Futuristic Lo-Fi Hip Hop')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('ambient lo-fi hip hop', 'lo-fi hip hop', 'Ambient Lo-Fi Hip Hop'),
('underground lo-fi hip hop', 'lo-fi hip hop', 'Underground Lo-Fi Hip Hop'),
('emotive lo-fi hip hop', 'lo-fi hip hop', 'Emotive Lo-Fi Hip Hop'),
('experimental lo-fi hip hop', 'lo-fi hip hop', 'Experimental Lo-Fi Hip Hop'),
('arabic lo-fi hip hop', 'lo-fi hip hop', 'Arabic Lo-Fi Hip Hop'),
('japanese lo-fi hip hop', 'lo-fi hip hop', 'Japanese Lo-Fi Hip Hop'),
('andean lo-fi hip hop', 'lo-fi hip hop', 'Andean Lo-Fi Hip Hop'),
('brazilian lo-fi hip hop', 'lo-fi hip hop', 'Brazilian Lo-Fi Hip Hop'),
('balkan lo-fi hip hop', 'lo-fi hip hop', 'Balkan Lo-Fi Hip Hop'),
('cuban lo-fi hip hop', 'lo-fi hip hop', 'Cuban Lo-Fi Hip Hop'),
('indian lo-fi hip hop', 'lo-fi hip hop', 'Indian Lo-Fi Hip Hop'),
('nigerian lo-fi hip hop', 'lo-fi hip hop', 'Nigerian Lo-Fi Hip Hop'),
('70s lo-fi hip hop', 'lo-fi hip hop', '70s Lo-Fi Hip Hop'),
('80s lo-fi hip hop', 'lo-fi hip hop', '80s Lo-Fi Hip Hop'),
('90s lo-fi hip hop', 'lo-fi hip hop', '90s Lo-Fi Hip Hop'),
('2000s lo-fi hip hop', 'lo-fi hip hop', '2000s Lo-Fi Hip Hop'),
('2010s lo-fi hip hop', 'lo-fi hip hop', '2010s Lo-Fi Hip Hop'),
('2020s lo-fi hip hop', 'lo-fi hip hop', '2020s Lo-Fi Hip Hop'),
('lo-fi hip hop / jazz fusion', 'lo-fi hip hop', 'Lo-Fi Hip Hop / Jazz Fusion'),
('lo-fi hip hop / rock fusion', 'lo-fi hip hop', 'Lo-Fi Hip Hop / Rock Fusion'),
('lo-fi hip hop / soul fusion', 'lo-fi hip hop', 'Lo-Fi Hip Hop / Soul Fusion'),
('lo-fi hip hop / funk fusion', 'lo-fi hip hop', 'Lo-Fi Hip Hop / Funk Fusion'),
('modern phonk', 'phonk', 'Modern Phonk'),
('organic phonk', 'phonk', 'Organic Phonk'),
('ambient phonk', 'phonk', 'Ambient Phonk'),
('futuristic phonk', 'phonk', 'Futuristic Phonk'),
('chill phonk', 'phonk', 'Chill Phonk'),
('melodic phonk', 'phonk', 'Melodic Phonk'),
('dark phonk', 'phonk', 'Dark Phonk'),
('orchestral phonk', 'phonk', 'Orchestral Phonk'),
('retro phonk', 'phonk', 'Retro Phonk'),
('emotive phonk', 'phonk', 'Emotive Phonk'),
('hard phonk', 'phonk', 'Hard Phonk'),
('lo-fi phonk', 'phonk', 'Lo-Fi Phonk'),
('ghanaian phonk', 'phonk', 'Ghanaian Phonk'),
('korean phonk', 'phonk', 'Korean Phonk'),
('turkish phonk', 'phonk', 'Turkish Phonk'),
('cuban phonk', 'phonk', 'Cuban Phonk'),
('caribbean phonk', 'phonk', 'Caribbean Phonk'),
('uk phonk', 'phonk', 'UK Phonk'),
('south african phonk', 'phonk', 'South African Phonk'),
('spanish phonk', 'phonk', 'Spanish Phonk'),
('70s phonk', 'phonk', '70s Phonk'),
('80s phonk', 'phonk', '80s Phonk'),
('90s phonk', 'phonk', '90s Phonk'),
('2000s phonk', 'phonk', '2000s Phonk'),
('2010s phonk', 'phonk', '2010s Phonk'),
('2020s phonk', 'phonk', '2020s Phonk'),
('phonk / hip hop fusion', 'phonk', 'Phonk / Hip Hop Fusion'),
('phonk / rock fusion', 'phonk', 'Phonk / Rock Fusion')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('phonk / soul fusion', 'phonk', 'Phonk / Soul Fusion'),
('phonk / classical fusion', 'phonk', 'Phonk / Classical Fusion'),
('phonk / latin fusion', 'phonk', 'Phonk / Latin Fusion'),
('progressive dance pop', 'dance pop', 'Progressive Dance Pop'),
('underground dance pop', 'dance pop', 'Underground Dance Pop'),
('classic dance pop', 'dance pop', 'Classic Dance Pop'),
('hard dance pop', 'dance pop', 'Hard Dance Pop'),
('minimal dance pop', 'dance pop', 'Minimal Dance Pop'),
('orchestral dance pop', 'dance pop', 'Orchestral Dance Pop'),
('modern dance pop', 'dance pop', 'Modern Dance Pop'),
('bright dance pop', 'dance pop', 'Bright Dance Pop'),
('melodic dance pop', 'dance pop', 'Melodic Dance Pop'),
('vintage dance pop', 'dance pop', 'Vintage Dance Pop'),
('retro dance pop', 'dance pop', 'Retro Dance Pop'),
('chill dance pop', 'dance pop', 'Chill Dance Pop'),
('balkan dance pop', 'dance pop', 'Balkan Dance Pop'),
('japanese dance pop', 'dance pop', 'Japanese Dance Pop'),
('south african dance pop', 'dance pop', 'South African Dance Pop'),
('german dance pop', 'dance pop', 'German Dance Pop'),
('korean dance pop', 'dance pop', 'Korean Dance Pop'),
('cuban dance pop', 'dance pop', 'Cuban Dance Pop'),
('brazilian dance pop', 'dance pop', 'Brazilian Dance Pop'),
('turkish dance pop', 'dance pop', 'Turkish Dance Pop'),
('70s dance pop', 'dance pop', '70s Dance Pop'),
('80s dance pop', 'dance pop', '80s Dance Pop'),
('90s dance pop', 'dance pop', '90s Dance Pop'),
('2000s dance pop', 'dance pop', '2000s Dance Pop'),
('2010s dance pop', 'dance pop', '2010s Dance Pop'),
('2020s dance pop', 'dance pop', '2020s Dance Pop'),
('dance pop / classical fusion', 'dance pop', 'Dance Pop / Classical Fusion'),
('dance pop / soul fusion', 'dance pop', 'Dance Pop / Soul Fusion'),
('dance pop / hip hop fusion', 'dance pop', 'Dance Pop / Hip Hop Fusion'),
('dance pop / funk fusion', 'dance pop', 'Dance Pop / Funk Fusion'),
('dance pop / rock fusion', 'dance pop', 'Dance Pop / Rock Fusion'),
('atmospheric synthpop', 'synthpop', 'Atmospheric Synthpop'),
('minimal synthpop', 'synthpop', 'Minimal Synthpop'),
('classic synthpop', 'synthpop', 'Classic Synthpop'),
('retro synthpop', 'synthpop', 'Retro Synthpop'),
('organic synthpop', 'synthpop', 'Organic Synthpop'),
('downtempo synthpop', 'synthpop', 'Downtempo Synthpop'),
('electric synthpop', 'synthpop', 'Electric Synthpop'),
('hard synthpop', 'synthpop', 'Hard Synthpop'),
('bright synthpop', 'synthpop', 'Bright Synthpop'),
('chill synthpop', 'synthpop', 'Chill Synthpop'),
('dark synthpop', 'synthpop', 'Dark Synthpop'),
('progressive synthpop', 'synthpop', 'Progressive Synthpop'),
('nigerian synthpop', 'synthpop', 'Nigerian Synthpop'),
('cuban synthpop', 'synthpop', 'Cuban Synthpop'),
('south african synthpop', 'synthpop', 'South African Synthpop'),
('nordic synthpop', 'synthpop', 'Nordic Synthpop')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('spanish synthpop', 'synthpop', 'Spanish Synthpop'),
('mexican synthpop', 'synthpop', 'Mexican Synthpop'),
('us synthpop', 'synthpop', 'US Synthpop'),
('indian synthpop', 'synthpop', 'Indian Synthpop'),
('70s synthpop', 'synthpop', '70s Synthpop'),
('80s synthpop', 'synthpop', '80s Synthpop'),
('90s synthpop', 'synthpop', '90s Synthpop'),
('2000s synthpop', 'synthpop', '2000s Synthpop'),
('2010s synthpop', 'synthpop', '2010s Synthpop'),
('2020s synthpop', 'synthpop', '2020s Synthpop'),
('synthpop / jazz fusion', 'synthpop', 'Synthpop / Jazz Fusion'),
('synthpop / funk fusion', 'synthpop', 'Synthpop / Funk Fusion'),
('synthpop / ambient fusion', 'synthpop', 'Synthpop / Ambient Fusion'),
('synthpop / classical fusion', 'synthpop', 'Synthpop / Classical Fusion'),
('synthpop / latin fusion', 'synthpop', 'Synthpop / Latin Fusion'),
('modern electropop', 'electropop', 'Modern Electropop'),
('uplifting electropop', 'electropop', 'Uplifting Electropop'),
('downtempo electropop', 'electropop', 'Downtempo Electropop'),
('dark electropop', 'electropop', 'Dark Electropop'),
('minimal electropop', 'electropop', 'Minimal Electropop'),
('melodic electropop', 'electropop', 'Melodic Electropop'),
('ambient electropop', 'electropop', 'Ambient Electropop'),
('vintage electropop', 'electropop', 'Vintage Electropop'),
('hard electropop', 'electropop', 'Hard Electropop'),
('organic electropop', 'electropop', 'Organic Electropop'),
('progressive electropop', 'electropop', 'Progressive Electropop'),
('electric electropop', 'electropop', 'Electric Electropop'),
('us electropop', 'electropop', 'US Electropop'),
('korean electropop', 'electropop', 'Korean Electropop'),
('ghanaian electropop', 'electropop', 'Ghanaian Electropop'),
('uk electropop', 'electropop', 'UK Electropop'),
('brazilian electropop', 'electropop', 'Brazilian Electropop'),
('nigerian electropop', 'electropop', 'Nigerian Electropop'),
('french electropop', 'electropop', 'French Electropop'),
('indian electropop', 'electropop', 'Indian Electropop'),
('70s electropop', 'electropop', '70s Electropop'),
('80s electropop', 'electropop', '80s Electropop'),
('90s electropop', 'electropop', '90s Electropop'),
('2000s electropop', 'electropop', '2000s Electropop'),
('2010s electropop', 'electropop', '2010s Electropop'),
('2020s electropop', 'electropop', '2020s Electropop'),
('electropop / funk fusion', 'electropop', 'Electropop / Funk Fusion'),
('electropop / rock fusion', 'electropop', 'Electropop / Rock Fusion'),
('electropop / soul fusion', 'electropop', 'Electropop / Soul Fusion'),
('electropop / hip hop fusion', 'electropop', 'Electropop / Hip Hop Fusion'),
('modern indie pop', 'indie pop', 'Modern Indie Pop'),
('dark indie pop', 'indie pop', 'Dark Indie Pop'),
('melodic indie pop', 'indie pop', 'Melodic Indie Pop'),
('lo-fi indie pop', 'indie pop', 'Lo-Fi Indie Pop'),
('deep indie pop', 'indie pop', 'Deep Indie Pop')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('cinematic indie pop', 'indie pop', 'Cinematic Indie Pop'),
('classic indie pop', 'indie pop', 'Classic Indie Pop'),
('downtempo indie pop', 'indie pop', 'Downtempo Indie Pop'),
('orchestral indie pop', 'indie pop', 'Orchestral Indie Pop'),
('atmospheric indie pop', 'indie pop', 'Atmospheric Indie Pop'),
('uplifting indie pop', 'indie pop', 'Uplifting Indie Pop'),
('hard indie pop', 'indie pop', 'Hard Indie Pop'),
('japanese indie pop', 'indie pop', 'Japanese Indie Pop'),
('nigerian indie pop', 'indie pop', 'Nigerian Indie Pop'),
('ghanaian indie pop', 'indie pop', 'Ghanaian Indie Pop'),
('brazilian indie pop', 'indie pop', 'Brazilian Indie Pop'),
('spanish indie pop', 'indie pop', 'Spanish Indie Pop'),
('korean indie pop', 'indie pop', 'Korean Indie Pop'),
('french indie pop', 'indie pop', 'French Indie Pop'),
('nordic indie pop', 'indie pop', 'Nordic Indie Pop'),
('70s indie pop', 'indie pop', '70s Indie Pop'),
('80s indie pop', 'indie pop', '80s Indie Pop'),
('90s indie pop', 'indie pop', '90s Indie Pop'),
('2000s indie pop', 'indie pop', '2000s Indie Pop'),
('2010s indie pop', 'indie pop', '2010s Indie Pop'),
('2020s indie pop', 'indie pop', '2020s Indie Pop'),
('indie pop / classical fusion', 'indie pop', 'Indie Pop / Classical Fusion'),
('indie pop / jazz fusion', 'indie pop', 'Indie Pop / Jazz Fusion'),
('indie pop / ambient fusion', 'indie pop', 'Indie Pop / Ambient Fusion'),
('indie pop / hip hop fusion', 'indie pop', 'Indie Pop / Hip Hop Fusion'),
('indie pop / funk fusion', 'indie pop', 'Indie Pop / Funk Fusion'),
('bright hyperpop', 'hyperpop', 'Bright Hyperpop'),
('futuristic hyperpop', 'hyperpop', 'Futuristic Hyperpop'),
('downtempo hyperpop', 'hyperpop', 'Downtempo Hyperpop'),
('underground hyperpop', 'hyperpop', 'Underground Hyperpop'),
('modern hyperpop', 'hyperpop', 'Modern Hyperpop'),
('hard hyperpop', 'hyperpop', 'Hard Hyperpop'),
('cinematic hyperpop', 'hyperpop', 'Cinematic Hyperpop'),
('lo-fi hyperpop', 'hyperpop', 'Lo-Fi Hyperpop'),
('retro hyperpop', 'hyperpop', 'Retro Hyperpop'),
('melodic hyperpop', 'hyperpop', 'Melodic Hyperpop'),
('electric hyperpop', 'hyperpop', 'Electric Hyperpop'),
('progressive hyperpop', 'hyperpop', 'Progressive Hyperpop'),
('arabic hyperpop', 'hyperpop', 'Arabic Hyperpop'),
('indian hyperpop', 'hyperpop', 'Indian Hyperpop'),
('uk hyperpop', 'hyperpop', 'UK Hyperpop'),
('brazilian hyperpop', 'hyperpop', 'Brazilian Hyperpop'),
('turkish hyperpop', 'hyperpop', 'Turkish Hyperpop'),
('nigerian hyperpop', 'hyperpop', 'Nigerian Hyperpop'),
('nordic hyperpop', 'hyperpop', 'Nordic Hyperpop'),
('andean hyperpop', 'hyperpop', 'Andean Hyperpop'),
('70s hyperpop', 'hyperpop', '70s Hyperpop'),
('80s hyperpop', 'hyperpop', '80s Hyperpop'),
('90s hyperpop', 'hyperpop', '90s Hyperpop'),
('2000s hyperpop', 'hyperpop', '2000s Hyperpop')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('2010s hyperpop', 'hyperpop', '2010s Hyperpop'),
('2020s hyperpop', 'hyperpop', '2020s Hyperpop'),
('hyperpop / classical fusion', 'hyperpop', 'Hyperpop / Classical Fusion'),
('hyperpop / jazz fusion', 'hyperpop', 'Hyperpop / Jazz Fusion'),
('hyperpop / soul fusion', 'hyperpop', 'Hyperpop / Soul Fusion'),
('hyperpop / latin fusion', 'hyperpop', 'Hyperpop / Latin Fusion'),
('atmospheric salsa', 'salsa', 'Atmospheric Salsa'),
('classic salsa', 'salsa', 'Classic Salsa'),
('modern salsa', 'salsa', 'Modern Salsa'),
('ambient salsa', 'salsa', 'Ambient Salsa'),
('retro salsa', 'salsa', 'Retro Salsa'),
('dark salsa', 'salsa', 'Dark Salsa'),
('downtempo salsa', 'salsa', 'Downtempo Salsa'),
('uplifting salsa', 'salsa', 'Uplifting Salsa'),
('bright salsa', 'salsa', 'Bright Salsa'),
('experimental salsa', 'salsa', 'Experimental Salsa'),
('minimal salsa', 'salsa', 'Minimal Salsa'),
('chill salsa', 'salsa', 'Chill Salsa'),
('south african salsa', 'salsa', 'South African Salsa'),
('arabic salsa', 'salsa', 'Arabic Salsa'),
('korean salsa', 'salsa', 'Korean Salsa'),
('japanese salsa', 'salsa', 'Japanese Salsa'),
('brazilian salsa', 'salsa', 'Brazilian Salsa'),
('caribbean salsa', 'salsa', 'Caribbean Salsa'),
('german salsa', 'salsa', 'German Salsa'),
('indian salsa', 'salsa', 'Indian Salsa'),
('70s salsa', 'salsa', '70s Salsa'),
('80s salsa', 'salsa', '80s Salsa'),
('90s salsa', 'salsa', '90s Salsa'),
('2000s salsa', 'salsa', '2000s Salsa'),
('2010s salsa', 'salsa', '2010s Salsa'),
('2020s salsa', 'salsa', '2020s Salsa'),
('salsa / jazz fusion', 'salsa', 'Salsa / Jazz Fusion'),
('salsa / hip hop fusion', 'salsa', 'Salsa / Hip Hop Fusion'),
('salsa / rock fusion', 'salsa', 'Salsa / Rock Fusion'),
('salsa / pop fusion', 'salsa', 'Salsa / Pop Fusion'),
('salsa / funk fusion', 'salsa', 'Salsa / Funk Fusion'),
('vintage reggaeton', 'reggaeton', 'Vintage Reggaeton'),
('bright reggaeton', 'reggaeton', 'Bright Reggaeton'),
('lo-fi reggaeton', 'reggaeton', 'Lo-Fi Reggaeton'),
('melodic reggaeton', 'reggaeton', 'Melodic Reggaeton'),
('minimal reggaeton', 'reggaeton', 'Minimal Reggaeton'),
('futuristic reggaeton', 'reggaeton', 'Futuristic Reggaeton'),
('ambient reggaeton', 'reggaeton', 'Ambient Reggaeton'),
('emotive reggaeton', 'reggaeton', 'Emotive Reggaeton'),
('dark reggaeton', 'reggaeton', 'Dark Reggaeton'),
('progressive reggaeton', 'reggaeton', 'Progressive Reggaeton'),
('hard reggaeton', 'reggaeton', 'Hard Reggaeton'),
('experimental reggaeton', 'reggaeton', 'Experimental Reggaeton'),
('japanese reggaeton', 'reggaeton', 'Japanese Reggaeton')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('indian reggaeton', 'reggaeton', 'Indian Reggaeton'),
('andean reggaeton', 'reggaeton', 'Andean Reggaeton'),
('balkan reggaeton', 'reggaeton', 'Balkan Reggaeton'),
('french reggaeton', 'reggaeton', 'French Reggaeton'),
('cuban reggaeton', 'reggaeton', 'Cuban Reggaeton'),
('nigerian reggaeton', 'reggaeton', 'Nigerian Reggaeton'),
('uk reggaeton', 'reggaeton', 'UK Reggaeton'),
('70s reggaeton', 'reggaeton', '70s Reggaeton'),
('80s reggaeton', 'reggaeton', '80s Reggaeton'),
('90s reggaeton', 'reggaeton', '90s Reggaeton'),
('2000s reggaeton', 'reggaeton', '2000s Reggaeton'),
('2010s reggaeton', 'reggaeton', '2010s Reggaeton'),
('2020s reggaeton', 'reggaeton', '2020s Reggaeton'),
('reggaeton / classical fusion', 'reggaeton', 'Reggaeton / Classical Fusion'),
('reggaeton / ambient fusion', 'reggaeton', 'Reggaeton / Ambient Fusion'),
('reggaeton / funk fusion', 'reggaeton', 'Reggaeton / Funk Fusion'),
('reggaeton / pop fusion', 'reggaeton', 'Reggaeton / Pop Fusion'),
('reggaeton / jazz fusion', 'reggaeton', 'Reggaeton / Jazz Fusion'),
('modern bachata', 'bachata', 'Modern Bachata'),
('electric bachata', 'bachata', 'Electric Bachata'),
('ambient bachata', 'bachata', 'Ambient Bachata'),
('uplifting bachata', 'bachata', 'Uplifting Bachata'),
('vintage bachata', 'bachata', 'Vintage Bachata'),
('dark bachata', 'bachata', 'Dark Bachata'),
('emotive bachata', 'bachata', 'Emotive Bachata'),
('atmospheric bachata', 'bachata', 'Atmospheric Bachata'),
('deep bachata', 'bachata', 'Deep Bachata'),
('hard bachata', 'bachata', 'Hard Bachata'),
('acoustic bachata', 'bachata', 'Acoustic Bachata'),
('chill bachata', 'bachata', 'Chill Bachata'),
('nordic bachata', 'bachata', 'Nordic Bachata'),
('french bachata', 'bachata', 'French Bachata'),
('cuban bachata', 'bachata', 'Cuban Bachata'),
('caribbean bachata', 'bachata', 'Caribbean Bachata'),
('spanish bachata', 'bachata', 'Spanish Bachata'),
('mexican bachata', 'bachata', 'Mexican Bachata'),
('balkan bachata', 'bachata', 'Balkan Bachata'),
('korean bachata', 'bachata', 'Korean Bachata'),
('70s bachata', 'bachata', '70s Bachata'),
('80s bachata', 'bachata', '80s Bachata'),
('90s bachata', 'bachata', '90s Bachata'),
('2000s bachata', 'bachata', '2000s Bachata'),
('2010s bachata', 'bachata', '2010s Bachata'),
('2020s bachata', 'bachata', '2020s Bachata'),
('bachata / rock fusion', 'bachata', 'Bachata / Rock Fusion'),
('bachata / soul fusion', 'bachata', 'Bachata / Soul Fusion'),
('bachata / funk fusion', 'bachata', 'Bachata / Funk Fusion'),
('bachata / latin fusion', 'bachata', 'Bachata / Latin Fusion'),
('bachata / pop fusion', 'bachata', 'Bachata / Pop Fusion'),
('atmospheric cumbia', 'cumbia', 'Atmospheric Cumbia')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('emotive cumbia', 'cumbia', 'Emotive Cumbia'),
('futuristic cumbia', 'cumbia', 'Futuristic Cumbia'),
('electric cumbia', 'cumbia', 'Electric Cumbia'),
('melodic cumbia', 'cumbia', 'Melodic Cumbia'),
('progressive cumbia', 'cumbia', 'Progressive Cumbia'),
('modern cumbia', 'cumbia', 'Modern Cumbia'),
('organic cumbia', 'cumbia', 'Organic Cumbia'),
('dark cumbia', 'cumbia', 'Dark Cumbia'),
('retro cumbia', 'cumbia', 'Retro Cumbia'),
('chill cumbia', 'cumbia', 'Chill Cumbia'),
('deep cumbia', 'cumbia', 'Deep Cumbia'),
('turkish cumbia', 'cumbia', 'Turkish Cumbia'),
('nigerian cumbia', 'cumbia', 'Nigerian Cumbia'),
('andean cumbia', 'cumbia', 'Andean Cumbia'),
('cuban cumbia', 'cumbia', 'Cuban Cumbia'),
('german cumbia', 'cumbia', 'German Cumbia'),
('us cumbia', 'cumbia', 'US Cumbia'),
('french cumbia', 'cumbia', 'French Cumbia'),
('indian cumbia', 'cumbia', 'Indian Cumbia'),
('70s cumbia', 'cumbia', '70s Cumbia'),
('80s cumbia', 'cumbia', '80s Cumbia'),
('90s cumbia', 'cumbia', '90s Cumbia'),
('2000s cumbia', 'cumbia', '2000s Cumbia'),
('2010s cumbia', 'cumbia', '2010s Cumbia'),
('2020s cumbia', 'cumbia', '2020s Cumbia'),
('cumbia / ambient fusion', 'cumbia', 'Cumbia / Ambient Fusion'),
('cumbia / funk fusion', 'cumbia', 'Cumbia / Funk Fusion'),
('cumbia / latin fusion', 'cumbia', 'Cumbia / Latin Fusion'),
('cumbia / soul fusion', 'cumbia', 'Cumbia / Soul Fusion'),
('cumbia / rock fusion', 'cumbia', 'Cumbia / Rock Fusion'),
('dark bossa nova', 'bossa nova', 'Dark Bossa Nova'),
('classic bossa nova', 'bossa nova', 'Classic Bossa Nova'),
('retro bossa nova', 'bossa nova', 'Retro Bossa Nova'),
('chill bossa nova', 'bossa nova', 'Chill Bossa Nova'),
('deep bossa nova', 'bossa nova', 'Deep Bossa Nova'),
('acoustic bossa nova', 'bossa nova', 'Acoustic Bossa Nova'),
('atmospheric bossa nova', 'bossa nova', 'Atmospheric Bossa Nova'),
('hard bossa nova', 'bossa nova', 'Hard Bossa Nova'),
('vintage bossa nova', 'bossa nova', 'Vintage Bossa Nova'),
('progressive bossa nova', 'bossa nova', 'Progressive Bossa Nova'),
('organic bossa nova', 'bossa nova', 'Organic Bossa Nova'),
('orchestral bossa nova', 'bossa nova', 'Orchestral Bossa Nova'),
('mexican bossa nova', 'bossa nova', 'Mexican Bossa Nova'),
('caribbean bossa nova', 'bossa nova', 'Caribbean Bossa Nova'),
('ghanaian bossa nova', 'bossa nova', 'Ghanaian Bossa Nova'),
('south african bossa nova', 'bossa nova', 'South African Bossa Nova'),
('uk bossa nova', 'bossa nova', 'UK Bossa Nova'),
('nordic bossa nova', 'bossa nova', 'Nordic Bossa Nova'),
('turkish bossa nova', 'bossa nova', 'Turkish Bossa Nova'),
('korean bossa nova', 'bossa nova', 'Korean Bossa Nova')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('70s bossa nova', 'bossa nova', '70s Bossa Nova'),
('80s bossa nova', 'bossa nova', '80s Bossa Nova'),
('90s bossa nova', 'bossa nova', '90s Bossa Nova'),
('2000s bossa nova', 'bossa nova', '2000s Bossa Nova'),
('2010s bossa nova', 'bossa nova', '2010s Bossa Nova'),
('2020s bossa nova', 'bossa nova', '2020s Bossa Nova'),
('bossa nova / funk fusion', 'bossa nova', 'Bossa Nova / Funk Fusion'),
('bossa nova / pop fusion', 'bossa nova', 'Bossa Nova / Pop Fusion'),
('bossa nova / classical fusion', 'bossa nova', 'Bossa Nova / Classical Fusion'),
('bossa nova / rock fusion', 'bossa nova', 'Bossa Nova / Rock Fusion'),
('bossa nova / hip hop fusion', 'bossa nova', 'Bossa Nova / Hip Hop Fusion'),
('deep samba', 'samba', 'Deep Samba'),
('organic samba', 'samba', 'Organic Samba'),
('cinematic samba', 'samba', 'Cinematic Samba'),
('orchestral samba', 'samba', 'Orchestral Samba'),
('minimal samba', 'samba', 'Minimal Samba'),
('ambient samba', 'samba', 'Ambient Samba'),
('vintage samba', 'samba', 'Vintage Samba'),
('uplifting samba', 'samba', 'Uplifting Samba'),
('bright samba', 'samba', 'Bright Samba'),
('lo-fi samba', 'samba', 'Lo-Fi Samba'),
('acoustic samba', 'samba', 'Acoustic Samba'),
('melodic samba', 'samba', 'Melodic Samba'),
('korean samba', 'samba', 'Korean Samba'),
('arabic samba', 'samba', 'Arabic Samba'),
('andean samba', 'samba', 'Andean Samba'),
('us samba', 'samba', 'US Samba'),
('german samba', 'samba', 'German Samba'),
('balkan samba', 'samba', 'Balkan Samba'),
('spanish samba', 'samba', 'Spanish Samba'),
('caribbean samba', 'samba', 'Caribbean Samba'),
('70s samba', 'samba', '70s Samba'),
('80s samba', 'samba', '80s Samba'),
('90s samba', 'samba', '90s Samba'),
('2000s samba', 'samba', '2000s Samba'),
('2010s samba', 'samba', '2010s Samba'),
('2020s samba', 'samba', '2020s Samba'),
('samba / ambient fusion', 'samba', 'Samba / Ambient Fusion'),
('samba / funk fusion', 'samba', 'Samba / Funk Fusion'),
('samba / pop fusion', 'samba', 'Samba / Pop Fusion'),
('samba / rock fusion', 'samba', 'Samba / Rock Fusion'),
('samba / classical fusion', 'samba', 'Samba / Classical Fusion'),
('atmospheric bebop', 'bebop', 'Atmospheric Bebop'),
('uplifting bebop', 'bebop', 'Uplifting Bebop'),
('chill bebop', 'bebop', 'Chill Bebop'),
('modern bebop', 'bebop', 'Modern Bebop'),
('underground bebop', 'bebop', 'Underground Bebop'),
('futuristic bebop', 'bebop', 'Futuristic Bebop'),
('downtempo bebop', 'bebop', 'Downtempo Bebop'),
('hard bebop', 'bebop', 'Hard Bebop')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('melodic bebop', 'bebop', 'Melodic Bebop'),
('bright bebop', 'bebop', 'Bright Bebop'),
('minimal bebop', 'bebop', 'Minimal Bebop'),
('deep bebop', 'bebop', 'Deep Bebop'),
('indian bebop', 'bebop', 'Indian Bebop'),
('spanish bebop', 'bebop', 'Spanish Bebop'),
('caribbean bebop', 'bebop', 'Caribbean Bebop'),
('us bebop', 'bebop', 'US Bebop'),
('korean bebop', 'bebop', 'Korean Bebop'),
('japanese bebop', 'bebop', 'Japanese Bebop'),
('brazilian bebop', 'bebop', 'Brazilian Bebop'),
('french bebop', 'bebop', 'French Bebop'),
('70s bebop', 'bebop', '70s Bebop'),
('80s bebop', 'bebop', '80s Bebop'),
('90s bebop', 'bebop', '90s Bebop'),
('2000s bebop', 'bebop', '2000s Bebop'),
('2010s bebop', 'bebop', '2010s Bebop'),
('2020s bebop', 'bebop', '2020s Bebop'),
('bebop / ambient fusion', 'bebop', 'Bebop / Ambient Fusion'),
('bebop / soul fusion', 'bebop', 'Bebop / Soul Fusion'),
('bebop / classical fusion', 'bebop', 'Bebop / Classical Fusion'),
('bebop / hip hop fusion', 'bebop', 'Bebop / Hip Hop Fusion'),
('bebop / pop fusion', 'bebop', 'Bebop / Pop Fusion'),
('classic fusion', 'fusion', 'Classic Fusion'),
('cinematic fusion', 'fusion', 'Cinematic Fusion'),
('futuristic fusion', 'fusion', 'Futuristic Fusion'),
('minimal fusion', 'fusion', 'Minimal Fusion'),
('acoustic fusion', 'fusion', 'Acoustic Fusion'),
('deep fusion', 'fusion', 'Deep Fusion'),
('electric fusion', 'fusion', 'Electric Fusion'),
('lo-fi fusion', 'fusion', 'Lo-Fi Fusion'),
('atmospheric fusion', 'fusion', 'Atmospheric Fusion'),
('chill fusion', 'fusion', 'Chill Fusion'),
('uplifting fusion', 'fusion', 'Uplifting Fusion'),
('dark fusion', 'fusion', 'Dark Fusion'),
('spanish fusion', 'fusion', 'Spanish Fusion'),
('french fusion', 'fusion', 'French Fusion'),
('ghanaian fusion', 'fusion', 'Ghanaian Fusion'),
('cuban fusion', 'fusion', 'Cuban Fusion'),
('balkan fusion', 'fusion', 'Balkan Fusion'),
('arabic fusion', 'fusion', 'Arabic Fusion'),
('japanese fusion', 'fusion', 'Japanese Fusion'),
('turkish fusion', 'fusion', 'Turkish Fusion'),
('70s fusion', 'fusion', '70s Fusion'),
('80s fusion', 'fusion', '80s Fusion'),
('90s fusion', 'fusion', '90s Fusion'),
('2000s fusion', 'fusion', '2000s Fusion'),
('2010s fusion', 'fusion', '2010s Fusion'),
('2020s fusion', 'fusion', '2020s Fusion'),
('fusion / latin fusion', 'fusion', 'Fusion / Latin Fusion')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('fusion / pop fusion', 'fusion', 'Fusion / Pop Fusion'),
('fusion / hip hop fusion', 'fusion', 'Fusion / Hip Hop Fusion'),
('fusion / funk fusion', 'fusion', 'Fusion / Funk Fusion'),
('fusion / rock fusion', 'fusion', 'Fusion / Rock Fusion'),
('hard smooth jazz', 'smooth jazz', 'Hard Smooth Jazz'),
('progressive smooth jazz', 'smooth jazz', 'Progressive Smooth Jazz'),
('orchestral smooth jazz', 'smooth jazz', 'Orchestral Smooth Jazz'),
('dark smooth jazz', 'smooth jazz', 'Dark Smooth Jazz'),
('underground smooth jazz', 'smooth jazz', 'Underground Smooth Jazz'),
('bright smooth jazz', 'smooth jazz', 'Bright Smooth Jazz'),
('vintage smooth jazz', 'smooth jazz', 'Vintage Smooth Jazz'),
('emotive smooth jazz', 'smooth jazz', 'Emotive Smooth Jazz'),
('minimal smooth jazz', 'smooth jazz', 'Minimal Smooth Jazz'),
('deep smooth jazz', 'smooth jazz', 'Deep Smooth Jazz'),
('retro smooth jazz', 'smooth jazz', 'Retro Smooth Jazz'),
('classic smooth jazz', 'smooth jazz', 'Classic Smooth Jazz'),
('nordic smooth jazz', 'smooth jazz', 'Nordic Smooth Jazz'),
('caribbean smooth jazz', 'smooth jazz', 'Caribbean Smooth Jazz'),
('nigerian smooth jazz', 'smooth jazz', 'Nigerian Smooth Jazz'),
('korean smooth jazz', 'smooth jazz', 'Korean Smooth Jazz'),
('french smooth jazz', 'smooth jazz', 'French Smooth Jazz'),
('arabic smooth jazz', 'smooth jazz', 'Arabic Smooth Jazz'),
('uk smooth jazz', 'smooth jazz', 'UK Smooth Jazz'),
('japanese smooth jazz', 'smooth jazz', 'Japanese Smooth Jazz'),
('70s smooth jazz', 'smooth jazz', '70s Smooth Jazz'),
('80s smooth jazz', 'smooth jazz', '80s Smooth Jazz'),
('90s smooth jazz', 'smooth jazz', '90s Smooth Jazz'),
('2000s smooth jazz', 'smooth jazz', '2000s Smooth Jazz'),
('2010s smooth jazz', 'smooth jazz', '2010s Smooth Jazz'),
('2020s smooth jazz', 'smooth jazz', '2020s Smooth Jazz'),
('smooth jazz / latin fusion', 'smooth jazz', 'Smooth Jazz / Latin Fusion'),
('smooth jazz / hip hop fusion', 'smooth jazz', 'Smooth Jazz / Hip Hop Fusion'),
('smooth jazz / pop fusion', 'smooth jazz', 'Smooth Jazz / Pop Fusion'),
('smooth jazz / classical fusion', 'smooth jazz', 'Smooth Jazz / Classical Fusion'),
('cinematic latin jazz', 'latin jazz', 'Cinematic Latin Jazz'),
('uplifting latin jazz', 'latin jazz', 'Uplifting Latin Jazz'),
('dark latin jazz', 'latin jazz', 'Dark Latin Jazz'),
('electric latin jazz', 'latin jazz', 'Electric Latin Jazz'),
('minimal latin jazz', 'latin jazz', 'Minimal Latin Jazz'),
('chill latin jazz', 'latin jazz', 'Chill Latin Jazz'),
('classic latin jazz', 'latin jazz', 'Classic Latin Jazz'),
('retro latin jazz', 'latin jazz', 'Retro Latin Jazz'),
('progressive latin jazz', 'latin jazz', 'Progressive Latin Jazz'),
('underground latin jazz', 'latin jazz', 'Underground Latin Jazz'),
('orchestral latin jazz', 'latin jazz', 'Orchestral Latin Jazz'),
('melodic latin jazz', 'latin jazz', 'Melodic Latin Jazz'),
('andean latin jazz', 'latin jazz', 'Andean Latin Jazz'),
('cuban latin jazz', 'latin jazz', 'Cuban Latin Jazz'),
('french latin jazz', 'latin jazz', 'French Latin Jazz'),
('south african latin jazz', 'latin jazz', 'South African Latin Jazz')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('ghanaian latin jazz', 'latin jazz', 'Ghanaian Latin Jazz'),
('balkan latin jazz', 'latin jazz', 'Balkan Latin Jazz'),
('us latin jazz', 'latin jazz', 'US Latin Jazz'),
('brazilian latin jazz', 'latin jazz', 'Brazilian Latin Jazz'),
('70s latin jazz', 'latin jazz', '70s Latin Jazz'),
('80s latin jazz', 'latin jazz', '80s Latin Jazz'),
('90s latin jazz', 'latin jazz', '90s Latin Jazz'),
('2000s latin jazz', 'latin jazz', '2000s Latin Jazz'),
('2010s latin jazz', 'latin jazz', '2010s Latin Jazz'),
('2020s latin jazz', 'latin jazz', '2020s Latin Jazz'),
('latin jazz / ambient fusion', 'latin jazz', 'Latin Jazz / Ambient Fusion'),
('latin jazz / classical fusion', 'latin jazz', 'Latin Jazz / Classical Fusion'),
('latin jazz / rock fusion', 'latin jazz', 'Latin Jazz / Rock Fusion'),
('modern death metal', 'death metal', 'Modern Death Metal'),
('organic death metal', 'death metal', 'Organic Death Metal'),
('classic death metal', 'death metal', 'Classic Death Metal'),
('ambient death metal', 'death metal', 'Ambient Death Metal'),
('atmospheric death metal', 'death metal', 'Atmospheric Death Metal'),
('downtempo death metal', 'death metal', 'Downtempo Death Metal'),
('futuristic death metal', 'death metal', 'Futuristic Death Metal'),
('deep death metal', 'death metal', 'Deep Death Metal'),
('bright death metal', 'death metal', 'Bright Death Metal'),
('emotive death metal', 'death metal', 'Emotive Death Metal'),
('vintage death metal', 'death metal', 'Vintage Death Metal'),
('chill death metal', 'death metal', 'Chill Death Metal'),
('german death metal', 'death metal', 'German Death Metal'),
('us death metal', 'death metal', 'US Death Metal'),
('korean death metal', 'death metal', 'Korean Death Metal'),
('spanish death metal', 'death metal', 'Spanish Death Metal'),
('japanese death metal', 'death metal', 'Japanese Death Metal'),
('arabic death metal', 'death metal', 'Arabic Death Metal'),
('south african death metal', 'death metal', 'South African Death Metal'),
('turkish death metal', 'death metal', 'Turkish Death Metal'),
('70s death metal', 'death metal', '70s Death Metal'),
('80s death metal', 'death metal', '80s Death Metal'),
('90s death metal', 'death metal', '90s Death Metal'),
('2000s death metal', 'death metal', '2000s Death Metal'),
('2010s death metal', 'death metal', '2010s Death Metal'),
('2020s death metal', 'death metal', '2020s Death Metal'),
('death metal / funk fusion', 'death metal', 'Death Metal / Funk Fusion'),
('death metal / pop fusion', 'death metal', 'Death Metal / Pop Fusion'),
('death metal / latin fusion', 'death metal', 'Death Metal / Latin Fusion'),
('death metal / rock fusion', 'death metal', 'Death Metal / Rock Fusion'),
('death metal / hip hop fusion', 'death metal', 'Death Metal / Hip Hop Fusion'),
('modern black metal', 'black metal', 'Modern Black Metal'),
('classic black metal', 'black metal', 'Classic Black Metal'),
('uplifting black metal', 'black metal', 'Uplifting Black Metal'),
('ambient black metal', 'black metal', 'Ambient Black Metal'),
('orchestral black metal', 'black metal', 'Orchestral Black Metal'),
('melodic black metal', 'black metal', 'Melodic Black Metal')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('cinematic black metal', 'black metal', 'Cinematic Black Metal'),
('futuristic black metal', 'black metal', 'Futuristic Black Metal'),
('retro black metal', 'black metal', 'Retro Black Metal'),
('dark black metal', 'black metal', 'Dark Black Metal'),
('electric black metal', 'black metal', 'Electric Black Metal'),
('bright black metal', 'black metal', 'Bright Black Metal'),
('ghanaian black metal', 'black metal', 'Ghanaian Black Metal'),
('balkan black metal', 'black metal', 'Balkan Black Metal'),
('us black metal', 'black metal', 'US Black Metal'),
('uk black metal', 'black metal', 'UK Black Metal'),
('cuban black metal', 'black metal', 'Cuban Black Metal'),
('german black metal', 'black metal', 'German Black Metal'),
('nigerian black metal', 'black metal', 'Nigerian Black Metal'),
('indian black metal', 'black metal', 'Indian Black Metal'),
('70s black metal', 'black metal', '70s Black Metal'),
('80s black metal', 'black metal', '80s Black Metal'),
('90s black metal', 'black metal', '90s Black Metal'),
('2000s black metal', 'black metal', '2000s Black Metal'),
('2010s black metal', 'black metal', '2010s Black Metal'),
('2020s black metal', 'black metal', '2020s Black Metal'),
('black metal / classical fusion', 'black metal', 'Black Metal / Classical Fusion'),
('black metal / jazz fusion', 'black metal', 'Black Metal / Jazz Fusion'),
('black metal / pop fusion', 'black metal', 'Black Metal / Pop Fusion'),
('black metal / latin fusion', 'black metal', 'Black Metal / Latin Fusion'),
('black metal / hip hop fusion', 'black metal', 'Black Metal / Hip Hop Fusion'),
('lo-fi doom metal', 'doom metal', 'Lo-Fi Doom Metal'),
('melodic doom metal', 'doom metal', 'Melodic Doom Metal'),
('downtempo doom metal', 'doom metal', 'Downtempo Doom Metal'),
('cinematic doom metal', 'doom metal', 'Cinematic Doom Metal'),
('bright doom metal', 'doom metal', 'Bright Doom Metal'),
('organic doom metal', 'doom metal', 'Organic Doom Metal'),
('experimental doom metal', 'doom metal', 'Experimental Doom Metal'),
('ambient doom metal', 'doom metal', 'Ambient Doom Metal'),
('chill doom metal', 'doom metal', 'Chill Doom Metal'),
('orchestral doom metal', 'doom metal', 'Orchestral Doom Metal'),
('atmospheric doom metal', 'doom metal', 'Atmospheric Doom Metal'),
('emotive doom metal', 'doom metal', 'Emotive Doom Metal'),
('balkan doom metal', 'doom metal', 'Balkan Doom Metal'),
('french doom metal', 'doom metal', 'French Doom Metal'),
('mexican doom metal', 'doom metal', 'Mexican Doom Metal'),
('cuban doom metal', 'doom metal', 'Cuban Doom Metal'),
('arabic doom metal', 'doom metal', 'Arabic Doom Metal'),
('brazilian doom metal', 'doom metal', 'Brazilian Doom Metal'),
('andean doom metal', 'doom metal', 'Andean Doom Metal'),
('ghanaian doom metal', 'doom metal', 'Ghanaian Doom Metal'),
('70s doom metal', 'doom metal', '70s Doom Metal'),
('80s doom metal', 'doom metal', '80s Doom Metal'),
('90s doom metal', 'doom metal', '90s Doom Metal'),
('2000s doom metal', 'doom metal', '2000s Doom Metal'),
('2010s doom metal', 'doom metal', '2010s Doom Metal')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('2020s doom metal', 'doom metal', '2020s Doom Metal'),
('doom metal / latin fusion', 'doom metal', 'Doom Metal / Latin Fusion'),
('doom metal / soul fusion', 'doom metal', 'Doom Metal / Soul Fusion'),
('doom metal / rock fusion', 'doom metal', 'Doom Metal / Rock Fusion'),
('doom metal / pop fusion', 'doom metal', 'Doom Metal / Pop Fusion'),
('doom metal / funk fusion', 'doom metal', 'Doom Metal / Funk Fusion'),
('electric metalcore', 'metalcore', 'Electric Metalcore'),
('downtempo metalcore', 'metalcore', 'Downtempo Metalcore'),
('deep metalcore', 'metalcore', 'Deep Metalcore'),
('acoustic metalcore', 'metalcore', 'Acoustic Metalcore'),
('melodic metalcore', 'metalcore', 'Melodic Metalcore'),
('progressive metalcore', 'metalcore', 'Progressive Metalcore'),
('underground metalcore', 'metalcore', 'Underground Metalcore'),
('retro metalcore', 'metalcore', 'Retro Metalcore'),
('orchestral metalcore', 'metalcore', 'Orchestral Metalcore'),
('cinematic metalcore', 'metalcore', 'Cinematic Metalcore'),
('hard metalcore', 'metalcore', 'Hard Metalcore'),
('classic metalcore', 'metalcore', 'Classic Metalcore'),
('balkan metalcore', 'metalcore', 'Balkan Metalcore'),
('brazilian metalcore', 'metalcore', 'Brazilian Metalcore'),
('cuban metalcore', 'metalcore', 'Cuban Metalcore'),
('french metalcore', 'metalcore', 'French Metalcore'),
('nordic metalcore', 'metalcore', 'Nordic Metalcore'),
('turkish metalcore', 'metalcore', 'Turkish Metalcore'),
('uk metalcore', 'metalcore', 'UK Metalcore'),
('andean metalcore', 'metalcore', 'Andean Metalcore'),
('70s metalcore', 'metalcore', '70s Metalcore'),
('80s metalcore', 'metalcore', '80s Metalcore'),
('90s metalcore', 'metalcore', '90s Metalcore'),
('2000s metalcore', 'metalcore', '2000s Metalcore'),
('2010s metalcore', 'metalcore', '2010s Metalcore'),
('2020s metalcore', 'metalcore', '2020s Metalcore'),
('metalcore / classical fusion', 'metalcore', 'Metalcore / Classical Fusion'),
('metalcore / rock fusion', 'metalcore', 'Metalcore / Rock Fusion'),
('metalcore / soul fusion', 'metalcore', 'Metalcore / Soul Fusion'),
('metalcore / pop fusion', 'metalcore', 'Metalcore / Pop Fusion'),
('metalcore / hip hop fusion', 'metalcore', 'Metalcore / Hip Hop Fusion'),
('modern progressive metal', 'progressive metal', 'Modern Progressive Metal'),
('acoustic progressive metal', 'progressive metal', 'Acoustic Progressive Metal'),
('atmospheric progressive metal', 'progressive metal', 'Atmospheric Progressive Metal'),
('organic progressive metal', 'progressive metal', 'Organic Progressive Metal'),
('vintage progressive metal', 'progressive metal', 'Vintage Progressive Metal'),
('emotive progressive metal', 'progressive metal', 'Emotive Progressive Metal'),
('cinematic progressive metal', 'progressive metal', 'Cinematic Progressive Metal'),
('experimental progressive metal', 'progressive metal', 'Experimental Progressive Metal'),
('retro progressive metal', 'progressive metal', 'Retro Progressive Metal'),
('classic progressive metal', 'progressive metal', 'Classic Progressive Metal'),
('lo-fi progressive metal', 'progressive metal', 'Lo-Fi Progressive Metal'),
('futuristic progressive metal', 'progressive metal', 'Futuristic Progressive Metal'),
('caribbean progressive metal', 'progressive metal', 'Caribbean Progressive Metal')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('uk progressive metal', 'progressive metal', 'UK Progressive Metal'),
('nigerian progressive metal', 'progressive metal', 'Nigerian Progressive Metal'),
('french progressive metal', 'progressive metal', 'French Progressive Metal'),
('brazilian progressive metal', 'progressive metal', 'Brazilian Progressive Metal'),
('mexican progressive metal', 'progressive metal', 'Mexican Progressive Metal'),
('balkan progressive metal', 'progressive metal', 'Balkan Progressive Metal'),
('turkish progressive metal', 'progressive metal', 'Turkish Progressive Metal'),
('70s progressive metal', 'progressive metal', '70s Progressive Metal'),
('80s progressive metal', 'progressive metal', '80s Progressive Metal'),
('90s progressive metal', 'progressive metal', '90s Progressive Metal'),
('2000s progressive metal', 'progressive metal', '2000s Progressive Metal'),
('2010s progressive metal', 'progressive metal', '2010s Progressive Metal'),
('2020s progressive metal', 'progressive metal', '2020s Progressive Metal'),
('progressive metal / soul fusion', 'progressive metal', 'Progressive Metal / Soul Fusion'),
('progressive metal / hip hop fusion', 'progressive metal', 'Progressive Metal / Hip Hop Fusion'),
('progressive metal / pop fusion', 'progressive metal', 'Progressive Metal / Pop Fusion'),
('progressive metal / classical fusion', 'progressive metal', 'Progressive Metal / Classical Fusion'),
('progressive metal / funk fusion', 'progressive metal', 'Progressive Metal / Funk Fusion'),
('modern dark ambient', 'dark ambient', 'Modern Dark Ambient'),
('lo-fi dark ambient', 'dark ambient', 'Lo-Fi Dark Ambient'),
('atmospheric dark ambient', 'dark ambient', 'Atmospheric Dark Ambient'),
('progressive dark ambient', 'dark ambient', 'Progressive Dark Ambient'),
('orchestral dark ambient', 'dark ambient', 'Orchestral Dark Ambient'),
('cinematic dark ambient', 'dark ambient', 'Cinematic Dark Ambient'),
('melodic dark ambient', 'dark ambient', 'Melodic Dark Ambient'),
('hard dark ambient', 'dark ambient', 'Hard Dark Ambient'),
('experimental dark ambient', 'dark ambient', 'Experimental Dark Ambient'),
('uplifting dark ambient', 'dark ambient', 'Uplifting Dark Ambient'),
('andean dark ambient', 'dark ambient', 'Andean Dark Ambient'),
('us dark ambient', 'dark ambient', 'US Dark Ambient'),
('korean dark ambient', 'dark ambient', 'Korean Dark Ambient'),
('indian dark ambient', 'dark ambient', 'Indian Dark Ambient'),
('uk dark ambient', 'dark ambient', 'UK Dark Ambient'),
('nordic dark ambient', 'dark ambient', 'Nordic Dark Ambient'),
('caribbean dark ambient', 'dark ambient', 'Caribbean Dark Ambient'),
('french dark ambient', 'dark ambient', 'French Dark Ambient'),
('70s dark ambient', 'dark ambient', '70s Dark Ambient'),
('80s dark ambient', 'dark ambient', '80s Dark Ambient'),
('90s dark ambient', 'dark ambient', '90s Dark Ambient'),
('2000s dark ambient', 'dark ambient', '2000s Dark Ambient'),
('2010s dark ambient', 'dark ambient', '2010s Dark Ambient'),
('2020s dark ambient', 'dark ambient', '2020s Dark Ambient'),
('dark ambient / jazz fusion', 'dark ambient', 'Dark Ambient / Jazz Fusion'),
('dark ambient / latin fusion', 'dark ambient', 'Dark Ambient / Latin Fusion'),
('dark ambient / rock fusion', 'dark ambient', 'Dark Ambient / Rock Fusion'),
('dark ambient / hip hop fusion', 'dark ambient', 'Dark Ambient / Hip Hop Fusion'),
('dark ambient / pop fusion', 'dark ambient', 'Dark Ambient / Pop Fusion'),
('acoustic space ambient', 'space ambient', 'Acoustic Space Ambient'),
('classic space ambient', 'space ambient', 'Classic Space Ambient'),
('underground space ambient', 'space ambient', 'Underground Space Ambient')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('vintage space ambient', 'space ambient', 'Vintage Space Ambient'),
('bright space ambient', 'space ambient', 'Bright Space Ambient'),
('atmospheric space ambient', 'space ambient', 'Atmospheric Space Ambient'),
('emotive space ambient', 'space ambient', 'Emotive Space Ambient'),
('retro space ambient', 'space ambient', 'Retro Space Ambient'),
('organic space ambient', 'space ambient', 'Organic Space Ambient'),
('orchestral space ambient', 'space ambient', 'Orchestral Space Ambient'),
('downtempo space ambient', 'space ambient', 'Downtempo Space Ambient'),
('modern space ambient', 'space ambient', 'Modern Space Ambient'),
('brazilian space ambient', 'space ambient', 'Brazilian Space Ambient'),
('mexican space ambient', 'space ambient', 'Mexican Space Ambient'),
('andean space ambient', 'space ambient', 'Andean Space Ambient'),
('caribbean space ambient', 'space ambient', 'Caribbean Space Ambient'),
('south african space ambient', 'space ambient', 'South African Space Ambient'),
('french space ambient', 'space ambient', 'French Space Ambient'),
('indian space ambient', 'space ambient', 'Indian Space Ambient'),
('us space ambient', 'space ambient', 'US Space Ambient'),
('70s space ambient', 'space ambient', '70s Space Ambient'),
('80s space ambient', 'space ambient', '80s Space Ambient'),
('90s space ambient', 'space ambient', '90s Space Ambient'),
('2000s space ambient', 'space ambient', '2000s Space Ambient'),
('2010s space ambient', 'space ambient', '2010s Space Ambient'),
('2020s space ambient', 'space ambient', '2020s Space Ambient'),
('space ambient / soul fusion', 'space ambient', 'Space Ambient / Soul Fusion'),
('space ambient / latin fusion', 'space ambient', 'Space Ambient / Latin Fusion'),
('space ambient / classical fusion', 'space ambient', 'Space Ambient / Classical Fusion'),
('space ambient / hip hop fusion', 'space ambient', 'Space Ambient / Hip Hop Fusion'),
('space ambient / funk fusion', 'space ambient', 'Space Ambient / Funk Fusion'),
('acoustic drone ambient', 'drone ambient', 'Acoustic Drone Ambient'),
('organic drone ambient', 'drone ambient', 'Organic Drone Ambient'),
('classic drone ambient', 'drone ambient', 'Classic Drone Ambient'),
('dark drone ambient', 'drone ambient', 'Dark Drone Ambient'),
('atmospheric drone ambient', 'drone ambient', 'Atmospheric Drone Ambient'),
('progressive drone ambient', 'drone ambient', 'Progressive Drone Ambient'),
('hard drone ambient', 'drone ambient', 'Hard Drone Ambient'),
('experimental drone ambient', 'drone ambient', 'Experimental Drone Ambient'),
('retro drone ambient', 'drone ambient', 'Retro Drone Ambient'),
('lo-fi drone ambient', 'drone ambient', 'Lo-Fi Drone Ambient'),
('minimal drone ambient', 'drone ambient', 'Minimal Drone Ambient'),
('ghanaian drone ambient', 'drone ambient', 'Ghanaian Drone Ambient'),
('nordic drone ambient', 'drone ambient', 'Nordic Drone Ambient'),
('spanish drone ambient', 'drone ambient', 'Spanish Drone Ambient'),
('turkish drone ambient', 'drone ambient', 'Turkish Drone Ambient'),
('french drone ambient', 'drone ambient', 'French Drone Ambient'),
('brazilian drone ambient', 'drone ambient', 'Brazilian Drone Ambient'),
('nigerian drone ambient', 'drone ambient', 'Nigerian Drone Ambient'),
('japanese drone ambient', 'drone ambient', 'Japanese Drone Ambient'),
('70s drone ambient', 'drone ambient', '70s Drone Ambient'),
('80s drone ambient', 'drone ambient', '80s Drone Ambient'),
('90s drone ambient', 'drone ambient', '90s Drone Ambient')
ON CONFLICT (tag) DO NOTHING;

INSERT INTO genre_hierarchy (tag, parent_tag, display_name) VALUES
('2000s drone ambient', 'drone ambient', '2000s Drone Ambient'),
('2010s drone ambient', 'drone ambient', '2010s Drone Ambient'),
('2020s drone ambient', 'drone ambient', '2020s Drone Ambient'),
('drone ambient / funk fusion', 'drone ambient', 'Drone Ambient / Funk Fusion'),
('drone ambient / jazz fusion', 'drone ambient', 'Drone Ambient / Jazz Fusion'),
('drone ambient / rock fusion', 'drone ambient', 'Drone Ambient / Rock Fusion'),
('drone ambient / soul fusion', 'drone ambient', 'Drone Ambient / Soul Fusion'),
('drone ambient / classical fusion', 'drone ambient', 'Drone Ambient / Classical Fusion'),
('classic meditation', 'meditation', 'Classic Meditation'),
('bright meditation', 'meditation', 'Bright Meditation'),
('hard meditation', 'meditation', 'Hard Meditation'),
('uplifting meditation', 'meditation', 'Uplifting Meditation'),
('vintage meditation', 'meditation', 'Vintage Meditation'),
('minimal meditation', 'meditation', 'Minimal Meditation'),
('underground meditation', 'meditation', 'Underground Meditation'),
('futuristic meditation', 'meditation', 'Futuristic Meditation'),
('dark meditation', 'meditation', 'Dark Meditation'),
('modern meditation', 'meditation', 'Modern Meditation'),
('electric meditation', 'meditation', 'Electric Meditation'),
('experimental meditation', 'meditation', 'Experimental Meditation'),
('mexican meditation', 'meditation', 'Mexican Meditation'),
('nordic meditation', 'meditation', 'Nordic Meditation'),
('cuban meditation', 'meditation', 'Cuban Meditation'),
('nigerian meditation', 'meditation', 'Nigerian Meditation'),
('balkan meditation', 'meditation', 'Balkan Meditation'),
('brazilian meditation', 'meditation', 'Brazilian Meditation'),
('german meditation', 'meditation', 'German Meditation'),
('us meditation', 'meditation', 'US Meditation'),
('70s meditation', 'meditation', '70s Meditation'),
('80s meditation', 'meditation', '80s Meditation'),
('90s meditation', 'meditation', '90s Meditation'),
('2000s meditation', 'meditation', '2000s Meditation'),
('2010s meditation', 'meditation', '2010s Meditation'),
('2020s meditation', 'meditation', '2020s Meditation'),
('meditation / ambient fusion', 'meditation', 'Meditation / Ambient Fusion'),
('meditation / jazz fusion', 'meditation', 'Meditation / Jazz Fusion'),
('meditation / pop fusion', 'meditation', 'Meditation / Pop Fusion'),
('meditation / rock fusion', 'meditation', 'Meditation / Rock Fusion'),
('meditation / hip hop fusion', 'meditation', 'Meditation / Hip Hop Fusion')
ON CONFLICT (tag) DO NOTHING;

-- Mood/presentation tags (non-genre)
INSERT INTO genre_hierarchy (tag, parent_tag, display_name, is_canonical) VALUES
('calm', NULL, 'Calm', true),
('upbeat', NULL, 'Upbeat', true),
('instrumental', NULL, 'Instrumental', true),
('easy listening', NULL, 'Easy Listening', true)
ON CONFLICT (tag) DO NOTHING;
