import { useEffect, useState } from "preact/hooks";
import { adminApi, type AdminAuditEntry, type AdminDevice, type AdminIconJob, type AdminPage, type AdminStation, type ApiError } from "./api";

type Tab = "devices" | "audit" | "stations";
type Load<T> = { state: "idle" | "loading" | "ready" | "error"; page?: AdminPage<T>; };
const labels: Record<Tab, { title: string; hint: string; icon: string }> = {
  devices: { title: "Устройства", hint: "Подключения и активность", icon: "◈" },
  audit: { title: "Аудит", hint: "История действий", icon: "≡" },
  stations: { title: "Станции", hint: "Каталог и иконки", icon: "◉" },
};
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("ru-RU", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

/** Renders the in-memory-token administrator console as a same-origin Preact SPA. */
export function AdminApp() {
  const [token, setToken] = useState("");
  const [tab, setTab] = useState<Tab>("devices");
  const [loginError, setLoginError] = useState("");
  const [expired, setExpired] = useState(false);
  const clear = (message = false) => { setToken(""); setExpired(message); };
  if (!token) return <Login expired={expired} error={loginError} onLogin={async (username, password) => { setLoginError(""); try { const response = await adminApi.login(username, password); setToken(response.access_token); setExpired(false); } catch { setLoginError("Неверное имя пользователя или пароль, либо сервер временно недоступен."); } }} />;
  return <main class="admin-app">
    <aside class="admin-sidebar">
      <div class="admin-brand"><span class="admin-brand-mark">R</span><div><strong>ROCKSERVER</strong><span>CONTROL PLANE</span></div></div>
      <div class="admin-sidebar-label">Рабочая область</div>
      <nav class="admin-nav" aria-label="Разделы администрирования">
        {(Object.keys(labels) as Tab[]).map(value => <button type="button" class={tab === value ? "admin-nav-item active" : "admin-nav-item"} aria-current={tab === value ? "page" : undefined} onClick={() => setTab(value)}><span class="admin-nav-icon" aria-hidden="true">{labels[value].icon}</span><span><strong>{labels[value].title}</strong><small>{labels[value].hint}</small></span></button>)}
      </nav>
      <div class="admin-sidebar-footer"><span class="admin-status-dot" aria-hidden="true" />Система работает</div>
    </aside>
    <div class="admin-workspace">
      <header class="admin-topbar"><div><p class="admin-kicker">RockServer / Admin</p><h1>{labels[tab].title}</h1></div><div class="admin-topbar-actions"><span class="admin-session"><span class="admin-avatar">A</span><span><strong>Администратор</strong><small>Сеанс активен</small></span></span><button class="admin-logout" type="button" onClick={() => { void adminApi.logout(token).catch(() => undefined).finally(() => clear()); }}>Выйти</button></div></header>
      {expired && <p class="admin-alert" role="alert">Сеанс истёк. Войдите снова.</p>}
      <div class="admin-content">{tab === "devices" && <Devices token={token} onExpired={() => clear(true)} />}{tab === "audit" && <Audit token={token} onExpired={() => clear(true)} />}{tab === "stations" && <Stations token={token} onExpired={() => clear(true)} />}</div>
    </div>
  </main>;
}

function Login({ expired, error, onLogin }: { expired: boolean; error: string; onLogin: (username: string, password: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  return <main class="admin-login-page"><section class="admin-login-card"><div class="admin-brand admin-brand-dark"><span class="admin-brand-mark">R</span><div><strong>ROCKSERVER</strong><span>CONTROL PLANE</span></div></div><div class="admin-login-copy"><p class="admin-kicker">Защищённая зона</p><h1>Вход администратора</h1><p>Управляйте устройствами, каталогом и журналом событий из единого рабочего пространства.</p></div>{expired && <p class="admin-alert" role="alert">Сеанс истёк или отозван. Войдите снова.</p>}<form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); setBusy(true); void onLogin(String(fields.get("username") ?? ""), String(fields.get("password") ?? "")).finally(() => setBusy(false)); }}><label>Имя пользователя<input name="username" autoComplete="username" required placeholder="admin" /></label><label>Пароль<input name="password" type="password" autoComplete="current-password" required placeholder="••••••••" /></label><button class="admin-primary-button" disabled={busy}>{busy ? "Вход…" : "Войти в консоль"}<span aria-hidden="true">→</span></button></form>{error && <p class="admin-alert" role="alert">{error}</p>}<p class="admin-login-note"><span aria-hidden="true">●</span> Доступ только для авторизованных администраторов</p></section><aside class="admin-login-aside"><p class="admin-kicker">Внутренняя консоль</p><h2>Операционная картина RockServer</h2><p>Следите за подключениями, качеством каталога и действиями операторов без лишнего шума.</p><div class="admin-login-metric"><strong>24/7</strong><span>контроль доступности</span></div></aside></main>;
}

function usePage<T>(load: () => Promise<AdminPage<T>>, onExpired: () => void, deps: unknown[]) { const [view, setView] = useState<Load<T>>({ state: "loading" }); useEffect(() => { let current = true; setView({ state: "loading" }); void load().then(page => current && setView({ state: "ready", page })).catch(error => { if (!current) return; if ((error as ApiError).code === "authentication_required") onExpired(); else setView({ state: "error" }); }); return () => { current = false; }; }, deps); return view; }
function Pager<T>({ view, onPrevious, onNext, offset }: { view: Load<T>; onPrevious: () => void; onNext: () => void; offset: number }) { if (view.state === "loading") return <p class="admin-empty" aria-live="polite">Загрузка данных…</p>; if (view.state === "error") return <p class="admin-empty admin-error" role="alert">Не удалось загрузить данные.</p>; if (!view.page?.items.length) return <p class="admin-empty">Нет данных для отображения.</p>; return <div class="admin-pager"><span>Показано с {offset + 1}</span><div><button type="button" disabled={!offset} onClick={onPrevious}>← Назад</button><button type="button" disabled={!view.page.has_more} onClick={onNext}>Далее →</button></div></div>; }
function PanelHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div class="admin-panel-heading"><div><p class="admin-kicker">{eyebrow}</p><h2>{title}</h2></div><p>{description}</p></div>; }

function Devices({ token, onExpired }: { token: string; onExpired: () => void }) { const [offset, setOffset] = useState(0); const view = usePage<AdminDevice>(() => adminApi.devices(token, offset), onExpired, [token, offset]); return <section class="admin-panel" role="tabpanel"><PanelHeading eyebrow="Подключения" title="Подключенные устройства" description="Активность клиентов RockCast и RockMobile." /><div class="admin-table admin-device-table"><div class="admin-table-head"><span>Устройство</span><span>Тип</span><span>Состояние</span><span>Последняя активность</span></div>{view.page?.items.map(item => <article class="admin-table-row"><div class="admin-device-name"><span class="admin-device-icon">{item.product === "RockCast" ? "▣" : "▤"}</span><strong>{item.product} — {item.display_name}</strong></div><span class="admin-muted">{item.device_type}</span><span><i class={item.status === "active" ? "admin-status-dot" : "admin-status-dot muted"} />{item.status}</span><span class="admin-muted">{formatDate(item.last_seen_at ?? item.created_at)}</span></article>)}</div><Pager view={view} offset={offset} onPrevious={() => setOffset(Math.max(0, offset - 25))} onNext={() => setOffset(offset + 25)} /></section>; }

function Audit({ token, onExpired }: { token: string; onExpired: () => void }) { const [offset, setOffset] = useState(0); const [filters, setFilters] = useState({ from: "", until: "", action: "", outcome: "" }); const view = usePage<AdminAuditEntry>(() => adminApi.audit(token, offset, filters), onExpired, [token, offset, filters.from, filters.until, filters.action, filters.outcome]); return <section class="admin-panel" role="tabpanel"><PanelHeading eyebrow="Безопасность" title="Журнал аудита" description="Фильтруйте действия операторов и системные события." /><div class="admin-filters"><label>С<input type="datetime-local" value={filters.from} onInput={event => { setOffset(0); setFilters({ ...filters, from: event.currentTarget.value }); }} /></label><label>По<input type="datetime-local" value={filters.until} onInput={event => { setOffset(0); setFilters({ ...filters, until: event.currentTarget.value }); }} /></label><label>Действие<input value={filters.action} onInput={event => { setOffset(0); setFilters({ ...filters, action: event.currentTarget.value }); }} placeholder="Например, login" /></label><label>Итог<input value={filters.outcome} onInput={event => { setOffset(0); setFilters({ ...filters, outcome: event.currentTarget.value }); }} placeholder="success" /></label></div><div class="admin-table admin-audit-table"><div class="admin-table-head"><span>Действие</span><span>Итог</span><span>Время</span></div>{view.page?.items.map(item => <article class="admin-table-row"><strong>{item.action}</strong><span class="admin-pill">{item.outcome}</span><span class="admin-muted">{formatDate(item.occurred_at)}</span></article>)}</div><Pager view={view} offset={offset} onPrevious={() => setOffset(Math.max(0, offset - 25))} onNext={() => setOffset(offset + 25)} /></section>; }

function Stations({ token, onExpired }: { token: string; onExpired: () => void }) {
  const [offset, setOffset] = useState(0); const [query, setQuery] = useState(""); const [job, setJob] = useState<AdminIconJob | null>(); const [importError, setImportError] = useState(""); const [changingStation, setChangingStation] = useState(""); const [iconRevision, setIconRevision] = useState(0);
  const view = usePage<AdminStation>(() => adminApi.stations(token, offset, query), onExpired, [token, offset, query]);
  useEffect(() => { let current = true; void adminApi.latestIconImport(token).then(value => current && setJob(value)).catch(error => { if ((error as ApiError).code === "authentication_required") onExpired(); else current && setImportError("Не удалось прочитать статус импорта."); }); return () => { current = false; }; }, [token]);
  useEffect(() => { if (job?.status !== "running") return; const timer = window.setTimeout(() => { void adminApi.iconImport(token, job.id).then(setJob).catch(error => { if ((error as ApiError).code === "authentication_required") onExpired(); else setImportError("Не удалось обновить статус импорта."); }); }, 1000); return () => window.clearTimeout(timer); }, [job?.id, job?.status, token]);
  const startImport = () => { setImportError(""); void adminApi.startIconImport(token).then(setJob).catch(error => { if ((error as ApiError).code === "authentication_required") onExpired(); else setImportError("Не удалось запустить импорт. Проверьте, что серверу задана постоянная директория иконок."); }); };
  const changeIcon = (stationId: string, file: File) => { setImportError(""); setChangingStation(stationId); void adminApi.replaceStationIcon(token, stationId, file).then(() => setIconRevision(value => value + 1)).catch(error => { if ((error as ApiError).code === "authentication_required") onExpired(); else setImportError("Не удалось сохранить иконку. Разрешены PNG, JPEG, WebP и ICO до 2 МиБ."); }).finally(() => setChangingStation("")); };
  const deleteIcon = (stationId: string) => { if (!window.confirm("Удалить ручную иконку? Следующий импорт сможет снова использовать источник каталога.")) return; setImportError(""); setChangingStation(stationId); void adminApi.removeStationIcon(token, stationId).then(() => setIconRevision(value => value + 1)).catch(error => { if ((error as ApiError).code === "authentication_required") onExpired(); else setImportError("Не удалось удалить ручную иконку."); }).finally(() => setChangingStation("")); };
  return <section class="admin-panel" role="tabpanel"><PanelHeading eyebrow="Каталог" title="Радиостанции" description="Поиск, состояние и ручные иконки каталога." /><div class="admin-station-toolbar"><label class="admin-search">Поиск по названию или жанру<input value={query} onInput={event => { setOffset(0); setQuery(event.currentTarget.value); }} placeholder="Найти станцию…" /></label><button class="admin-secondary-button" type="button" disabled={job?.status === "running"} onClick={startImport}>{job?.status === "running" ? "Импорт выполняется…" : "Импортировать иконки"}</button></div>{job && <p class="admin-job" aria-live="polite"><span class="admin-status-dot" />{job.status === "running" ? "Импорт" : "Последний импорт"}: {job.processed} из {job.selected} · готово {job.ready} · без иконки {job.missing} · ошибок {job.retryable_error + job.permanent_error}</p>}{importError && <p class="admin-alert" role="alert">{importError}</p>}<div class="admin-table admin-station-table"><div class="admin-table-head"><span>Станция</span><span>Теги</span><span>Регион / состояние</span><span>Действия</span></div>{view.page?.items.map(item => <article class="admin-table-row"><div class="station-title"><span class="station-icon-frame"><span class="station-icon-placeholder" aria-hidden="true">◉</span><img key={`${item.station_id}-${iconRevision}`} class="station-icon" src={`/api/v1/stations/${encodeURIComponent(item.station_id)}/icon?revision=${iconRevision}`} alt="" onError={event => { event.currentTarget.hidden = true; }} /></span><strong>{item.name}</strong></div><span class="admin-muted">{item.tags.join(", ") || "—"}</span><span class="admin-muted">{item.language ?? "—"} · {item.country_code ?? "—"} · {item.health}</span><span class="station-icon-actions"><label class="admin-upload">Загрузить<input type="file" accept="image/png,image/jpeg,image/webp,image/x-icon,.ico" disabled={changingStation === item.station_id} onChange={event => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (file) changeIcon(item.station_id, file); }} /></label><button class="admin-text-button" type="button" disabled={changingStation === item.station_id} onClick={() => deleteIcon(item.station_id)}>Удалить</button></span></article>)}</div><Pager view={view} offset={offset} onPrevious={() => setOffset(Math.max(0, offset - 50))} onNext={() => setOffset(offset + 50)} /></section>;
}
