import { useEffect, useState } from "preact/hooks";
import { adminApi, type AdminAuditEntry, type AdminDevice, type AdminPage, type AdminStation, type ApiError } from "./api";

type Tab = "devices" | "audit" | "stations";
type Load<T> = { state: "idle" | "loading" | "ready" | "error"; page?: AdminPage<T>; };
const labels: Record<Tab, string> = { devices: "Устройства", audit: "Аудит", stations: "Станции" };
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("ru-RU", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

/** Renders the in-memory-token administrator console as a same-origin Preact SPA. */
export function AdminApp() {
  const [token, setToken] = useState("");
  const [tab, setTab] = useState<Tab>("devices");
  const [loginError, setLoginError] = useState("");
  const [expired, setExpired] = useState(false);
  const clear = (message = false) => { setToken(""); setExpired(message); };
  if (!token) return <Login expired={expired} error={loginError} onLogin={async (username, password) => { setLoginError(""); try { const response = await adminApi.login(username, password); setToken(response.access_token); setExpired(false); } catch { setLoginError("Неверное имя пользователя или пароль, либо сервер временно недоступен."); } }} />;
  return <main class="admin-shell"><header class="admin-header"><p class="brand">ROCKSERVER</p><h1>Администрирование</h1><button type="button" onClick={() => { void adminApi.logout(token).catch(() => undefined).finally(() => clear()); }}>Выйти</button></header>{expired && <p role="alert">Сеанс истёк. Войдите снова.</p>}<div role="tablist" aria-label="Разделы администрирования" class="admin-tabs">{(Object.keys(labels) as Tab[]).map(value => <button type="button" role="tab" aria-selected={tab === value} onClick={() => setTab(value)}>{labels[value]}</button>)}</div>{tab === "devices" && <Devices token={token} onExpired={() => clear(true)} />}{tab === "audit" && <Audit token={token} onExpired={() => clear(true)} />}{tab === "stations" && <Stations token={token} onExpired={() => clear(true)} />}</main>;
}

function Login({ expired, error, onLogin }: { expired: boolean; error: string; onLogin: (username: string, password: string) => Promise<void> }) { const [busy, setBusy] = useState(false); return <main class="admin-login"><p class="brand">ROCKSERVER</p><h1>Вход администратора</h1>{expired && <p role="alert">Сеанс истёк или отозван. Войдите снова.</p>}<form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); setBusy(true); void onLogin(String(fields.get("username") ?? ""), String(fields.get("password") ?? "")).finally(() => setBusy(false)); }}><label>Имя пользователя<input name="username" autoComplete="username" required /></label><label>Пароль<input name="password" type="password" autoComplete="current-password" required /></label><button disabled={busy}>{busy ? "Вход…" : "Войти"}</button></form>{error && <p role="alert">{error}</p>}</main>; }

function usePage<T>(load: () => Promise<AdminPage<T>>, onExpired: () => void, deps: unknown[]) { const [view, setView] = useState<Load<T>>({ state: "loading" }); useEffect(() => { let current = true; setView({ state: "loading" }); void load().then(page => current && setView({ state: "ready", page })).catch(error => { if (!current) return; if ((error as ApiError).code === "authentication_required") onExpired(); else setView({ state: "error" }); }); return () => { current = false; }; }, deps); return view; }
function Pager<T>({ view, onPrevious, onNext, offset }: { view: Load<T>; onPrevious: () => void; onNext: () => void; offset: number }) { if (view.state === "loading") return <p aria-live="polite">Загрузка…</p>; if (view.state === "error") return <p role="alert">Не удалось загрузить данные.</p>; if (!view.page?.items.length) return <p>Нет данных.</p>; return <><div class="admin-pager"><button disabled={!offset} onClick={onPrevious}>Назад</button><button disabled={!view.page.has_more} onClick={onNext}>Далее</button></div></>; }
function Devices({ token, onExpired }: { token: string; onExpired: () => void }) { const [offset, setOffset] = useState(0); const view = usePage<AdminDevice>(() => adminApi.devices(token, offset), onExpired, [token, offset]); return <section role="tabpanel"><h2>Подключенные устройства</h2><Pager view={view} offset={offset} onPrevious={() => setOffset(Math.max(0, offset - 25))} onNext={() => setOffset(offset + 25)} />{view.page?.items.map(item => <article class="admin-row"><strong>{item.product} — {item.display_name}</strong><span>{item.device_type} · {item.status}</span><span>Создано: {formatDate(item.created_at)}; активно: {formatDate(item.last_seen_at)}</span></article>)}</section>; }
function Audit({ token, onExpired }: { token: string; onExpired: () => void }) { const [offset, setOffset] = useState(0); const [filters, setFilters] = useState({ from: "", until: "", action: "", outcome: "" }); const view = usePage<AdminAuditEntry>(() => adminApi.audit(token, offset, filters), onExpired, [token, offset, filters.from, filters.until, filters.action, filters.outcome]); return <section role="tabpanel"><h2>Аудит</h2><div class="admin-filters"><label>С<input type="datetime-local" value={filters.from} onInput={event => { setOffset(0); setFilters({ ...filters, from: event.currentTarget.value }); }} /></label><label>По<input type="datetime-local" value={filters.until} onInput={event => { setOffset(0); setFilters({ ...filters, until: event.currentTarget.value }); }} /></label><label>Действие<input value={filters.action} onInput={event => { setOffset(0); setFilters({ ...filters, action: event.currentTarget.value }); }} /></label><label>Итог<input value={filters.outcome} onInput={event => { setOffset(0); setFilters({ ...filters, outcome: event.currentTarget.value }); }} /></label></div><Pager view={view} offset={offset} onPrevious={() => setOffset(Math.max(0, offset - 25))} onNext={() => setOffset(offset + 25)} />{view.page?.items.map(item => <article class="admin-row"><strong>{item.action}</strong><span>{item.outcome}</span><span>{formatDate(item.occurred_at)}</span></article>)}</section>; }
function Stations({ token, onExpired }: { token: string; onExpired: () => void }) { const [offset, setOffset] = useState(0); const [query, setQuery] = useState(""); const view = usePage<AdminStation>(() => adminApi.stations(token, offset, query), onExpired, [token, offset, query]); return <section role="tabpanel"><h2>Станции</h2><label>Поиск по названию или жанру<input value={query} onInput={event => { setOffset(0); setQuery(event.currentTarget.value); }} /></label><Pager view={view} offset={offset} onPrevious={() => setOffset(Math.max(0, offset - 25))} onNext={() => setOffset(offset + 25)} />{view.page?.items.map(item => <article class="admin-row"><strong>{item.name}</strong><span>{item.tags.join(", ") || "—"}</span><span>{item.language ?? "—"} · {item.country_code ?? "—"} · {item.health}</span></article>)}</section>; }
